AtB-AS/planner-web

package.json
src/layouts/global-data/index.ts
src/modules/api-client/index.ts
src/modules/api-client/utils.ts
src/page-modules/departures/api/autocomplete/encoders.ts
src/page-modules/departures/api/autocomplete/index.ts
src/page-modules/departures/api/index.ts
src/page-modules/departures/index.ts
src/pages/departures.tsx
src/translations/index.ts
src/translations/server/endpoints.ts
src/translations/server/index.ts
yarn.lock

Adding fundamental structure for how to integrate and get server data for pages and starting to establish overall architecture for modules.
Open for feedback on this. Somethings might seem more advanced types and structure, but trying to clean up consumption API for pages

feat: adds example structure for api intergration departure

---

src/modules/api-server/index.ts
src/pages/api/departures/autocomplete.ts

Changes to be able to use:
```ts
export default handlerWithDepartureClient<AutocompleteApiReturnType>({
async GET(req, res, { client, ok }) { },
async POST(req, res, { client, ok }) { },
// ... etc
});
```
And have it automatically return invalid method if nothing is matched. Simplifies HTTP verb handling for each API endpoint.

refactor: adds ability to support multiple http methods for endpoints

---

.env.example
.github/workflows/docker.yml
.github/workflows/test.yml
.github/workflows/tsc.yml
.gitignore
Dockerfile
README.md
next.config.js
package.json
scripts/build.sh
server.js
src/modules/org-data/index.tsx
src/pages/_error.tsx

- Temporary Error Page: 
I've added a temporary error page so that the application can be built without errors
- Rename env variable: 
I've renamed the environment variable from `NEXT_PUBLIC_WEBSHOP_ORG_ID` to `NEXT_PUBLIC_PLANNER_ORG_ID`
- Build: 
New script in the package.json file: build:all. This runs the new build.sh script that creates a standalone build for all organizations and stores it in the dist directory.
- Docker Image: 
I've added a Dockerfile that creates a single image that can be used to serve all organizations. The new server.js file now determines the decision on which organization to run.
Note: I've tested that each organization handles the assets correctly. However, the theme is not functioning as expected. It's worth noting that this issue persists even when using …

build: add build and deployment automation

---

.github/workflows/docker.yml

We need to specify which overlays we push to, to ensure that the system will pick up new versions. 
Ref: https://github.com/AtB-AS/gcp-infra/pull/415#pullrequestreview-1643544450

build: specify overlays for each org

---

.github/workflows/docker.yml

This reverts commit 17323c644475568f091d04472b0f25d61dc8ac2c. As we are pushing for all tenants at the same time I am in the process of moving the kustomization to base and we won't need to specify overlays (https://github.com/AtB-AS/gcp-infra/pull/419). 
For future references, it's not necessary to use a matrix to specify the push and release overlays. It can be done so:
```yaml
with:
image: gcr.io/atb-mobility-platform/planner-web
push_overlay: atb-staging-c420 nfk-staging-dac7 fram-staging-dc00
release_overlay: atb-prod-2e7e nfk-prod-ce66 fram-prod-019b
overlays_base: manifests/amp/overlays
```

Revert "build: specify overlays for each org (#13)"

---

src/modules/api-server/__tests__/utils.test.ts
src/modules/api-server/index.ts
src/modules/api-server/utils.ts

If client passes correlation id or install id, pass it along to the server (having transient communication of correlation ids)

feat: pass on correlation and install id from incoming request for client

---

src/components/departure-date-selector/__tests__/departure-date-selector.test.tsx
src/components/departure-date-selector/departure-date-selector.module.css
src/components/departure-date-selector/index.tsx
src/page-modules/departures/departures.module.css
src/page-modules/departures/layout.tsx
src/translations/components/departure-date-selector.ts
src/translations/components/index.ts
src/translations/pages/departures.ts

Added options for when to travel, based on the current time, the arrival time or the departure time.
<details><summary>Screenshots</summary>
</details> 
Fixes https://github.com/AtB-AS/kundevendt/issues/9144 (parts of it)

feat: add departure date selector

---

src/page-modules/departures/nearest-stop-places/nearest-stop-places.module.css

This makes it so that the map container is max 600px.

fix: map container max height on departures page

---

src/components/map/__tests__/map.test.tsx
src/components/map/map-header.tsx
src/components/map/map.module.css
src/components/transport-mode/transport-icon/index.tsx
src/page-modules/departures/nearest-stop-places/index.tsx
src/page-modules/departures/stop-place/index.tsx

This PR updates the MapHeader icons from FeatureCategory to TransportMode to fit better with the StopPlace type. I also removed the street property from the MapHeader as this doesn't exist on the StopPlace object. I'll ask the designer what we should do about the subtitle in the header, but for now, I think it's better to remove it and don't use the question mark as a placeholder. 
Closes https://github.com/AtB-AS/kundevendt/issues/11279
<details>
</details>

refactor: map header icons and text

---

src/components/search/__tests__/search.test.tsx
src/components/search/index.tsx
src/components/search/search.module.css
src/components/search/swap-button/index.tsx
src/layouts/shared/page-header.tsx
src/page-modules/assistant/__tests__/assistant.test.tsx
src/page-modules/assistant/assistant.module.css
src/page-modules/assistant/index.ts
src/page-modules/assistant/layout.tsx
src/page-modules/assistant/server/index.ts
src/page-modules/assistant/server/journey-planner/index.ts
src/page-modules/assistant/server/journey-planner/journey-gql/trip.gql
src/page-modules/assistant/server/journey-planner/validators.ts
src/page-modules/assistant/types.ts
src/page-modules/assistant/utils.ts
src/page-modules/departures/departures.module.css
src/page-modules/departures/layout.tsx
src/page-modules/departures/server/geocoder/index.ts
src/page-modules/departures/server/journey-planner/index.ts
src/pages/api/departures/reverse.ts
src/pages/assistant/assistant.module.css
src/pages/assistant/index.tsx
src/pages/departures/[[...id]].tsx
src/translations/components/index.ts
src/translations/components/swap-button.ts
src/translations/pages/assistant.ts
src/translations/pages/index.ts

This includes the assistant page header and the required functionality to get a trip with trip patterns. We might want to fine-tune the data included in a trip, but that might be easier to do when we start to work on the assistant page content. The search is stored in the URL. 
Closes https://github.com/AtB-AS/kundevendt/issues/11317
<details>
</details>

feat: assistant page header

---

src/components/icon/mono-icon.tsx
src/page-modules/assistant/trip-pattern/index.tsx

There was a bug in setting the `darkModeString` for `MonoIcon`. The hook `useInteractiveThemeColor` returned `undefined` instead of `none`, which caused issues.

fix: fix bug in MonoIcon dark mode

---

src/components/button/button.module.css
src/components/button/utils.tsx
src/components/map/map-header.tsx
src/components/transport-mode/index.ts
src/components/transport-mode/transport-icon/index.tsx
src/components/transport-mode/types.ts
src/page-modules/assistant/__tests__/assistant.test.tsx
src/page-modules/assistant/assistant.module.css
src/page-modules/assistant/index.ts
src/page-modules/assistant/non-transit-pill/index.tsx
src/page-modules/assistant/server/journey-planner/index.ts
src/page-modules/assistant/server/journey-planner/journey-gql/trip.gql
src/page-modules/assistant/server/journey-planner/validators.ts
src/page-modules/assistant/types.ts
src/page-modules/departures/server/journey-planner/index.ts
src/page-modules/departures/server/journey-planner/validators.ts
src/pages/assistant/index.tsx
src/translations/pages/assistant.ts
src/utils/date.ts

Adds non-transit search results and removes walking from original trip result.
Not happy about `TransportModeType`, `TransportSubmodeType` usage inside components. Want to refactor, but seeing if that could be separate PR.
Assistant page should be handled better but see that that work is done in #45 , so leaving as is for now.
Fixes https://github.com/AtB-AS/kundevendt/issues/11320
<details><summary>Screenshot</summary>
<p>
</p>
</details>

feat: adds non-transit data to trip patterns.

---

src/page-modules/assistant/__tests__/assistant.test.tsx
src/page-modules/assistant/__tests__/test-data.ts
src/page-modules/assistant/server/journey-planner/validators.ts
src/page-modules/assistant/trip/index.tsx
src/page-modules/assistant/trip/trip-pattern-header/__tests__/trip-pattern-header.test.tsx
src/page-modules/assistant/trip/trip-pattern-header/__tests__/trip.fixture.ts
src/page-modules/assistant/trip/trip-pattern-header/index.tsx
src/page-modules/assistant/trip/trip-pattern-header/trip-pattern-header.module.css
src/page-modules/assistant/trip/trip.module.css
src/page-modules/assistant/utils.ts
src/page-modules/departures/__tests__/departure-data.fixture.ts
src/page-modules/departures/__tests__/departure.test.tsx
src/translations/pages/assistant.ts

This PR introduces a valuable new feature which dynamically bases the trip pattern header text on the mode of the first leg of the journey. It seeks to enhance the user experience by providing a clearer, context-aware narrative about the upcoming trip details.
Fixes https://github.com/AtB-AS/kundevendt/issues/14917

feat: base trip pattern header text on mode of first leg

---

src/page-modules/assistant/client/journey-planner/index.ts
src/page-modules/assistant/layout.tsx
src/page-modules/assistant/server/journey-planner/index.ts
src/page-modules/assistant/trip/index.tsx
src/page-modules/assistant/trip/trip.module.css
src/page-modules/assistant/utils.ts
src/translations/pages/assistant.ts
src/utils/date.ts

With this PR we now search for trip patterns until we have found at least 5 trip patterns, with a maximum of 15 attempts. I have also added a day label to the trip patterns list so that it's easier to distinguish day of travel. 
<details>
</details>

feat: recursive trip pattern search and day label in trip pattern list

---

src/components/empty-search-results/empty-search-results.module.css
src/components/empty-search-results/index.tsx
src/page-modules/assistant/__tests__/assistant-data.fixture.ts
src/page-modules/assistant/__tests__/assistant.test.tsx
src/page-modules/assistant/trip/index.tsx
src/page-modules/departures/__tests__/departure.test.tsx
src/page-modules/departures/nearest-stop-places/index.tsx
src/translations/pages/assistant.ts
src/translations/pages/departures.ts

This introduces a component for handling empty search results. 
Fixes sub-task "Add information on empty results" for https://github.com/AtB-AS/kundevendt/issues/11319 
<details>
</details>

feat: empty search results component

---

src/page-modules/assistant/assistant.module.css
src/page-modules/assistant/layout.tsx
src/page-modules/departures/departures.module.css
src/page-modules/departures/layout.tsx
src/translations/pages/assistant.ts
src/translations/pages/departures.ts

This PR introduces searching state information when searching for travel patterns and stop places. I've added a loading indicator to the search button and a text about loading travel suggestions/stop places/departures according to the design sketches.  
Fixes https://github.com/AtB-AS/kundevendt/issues/14924
TODO:

feat: loading indicator when searching for travels and stop places

---

src/page-modules/assistant/__tests__/assistant-data.fixture.ts
src/page-modules/assistant/non-transit-pill/index.tsx
src/page-modules/assistant/server/journey-planner/index.ts
src/page-modules/assistant/server/journey-planner/journey-gql/trip.gql
src/page-modules/assistant/server/journey-planner/validators.ts
src/page-modules/assistant/trip/index.tsx
src/page-modules/assistant/types.ts

Only pass on what is needed for showing non-transit suggestions.
Needs to be extended when the detail page is implemented (with added key/id)

refactor: removes loads of unused data

---

src/modules/situations/index.ts
src/modules/situations/situation-or-notice-icon.tsx
src/modules/situations/types.ts
src/modules/situations/utils.ts
src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/index.tsx
src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/rail-replacement-bus.tsx
src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/trip-pattern-header.module.css
src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/utils.ts
src/translations/pages/assistant.ts
src/utils/only-uniques.ts

Show an icon when there's a situation or notice for the trip pattern. The icon is shown in the top right corner of a trip card.
Logic from the app is reused to maintain the same functionality across platforms.
Did an attempt to create a modue for situations and notices since there probably will be more coming for that, for the details page etc. Not sure if this is the way modules should be handled though.
Note: branched this off of the other PR, since the folder structure have been altered some. 
Fixes https://github.com/AtB-AS/kundevendt/issues/14919

feat: show icon for situation or notice

---

src/modules/search-time/selector/__tests__/selector.test.tsx
src/modules/search-time/selector/index.tsx
src/modules/search-time/selector/selector.module.css
src/page-modules/departures/layout.tsx

Added a prop to allow not showing all the options in the search time selector. E.g. for the departures page we (most likely) don't want to show "Arrival" since it does not make sense in terms of showing departures for stop places.

feat: allow not showing an option in search time selector

---

src/modules/search-time/index.ts
src/modules/search-time/utils.ts
src/page-modules/departures/__tests__/departure.test.tsx
src/page-modules/departures/layout.tsx
src/page-modules/departures/server/journey-planner/index.ts
src/pages/departures/[[...id]].tsx

Adds initial state for the search bar and date selector on the departures page. Without the initial state it didn't matter what was in the query.

feat: add initial state for search and date to departures page

---

src/page-modules/departures/client/journey-planner/index.ts
src/page-modules/departures/server/journey-planner/index.ts
src/page-modules/departures/server/journey-planner/journey-gql/estimated-calls.gql
src/page-modules/departures/stop-place/index.tsx
src/pages/api/departures/journey-planner.ts

Adds transport modes as a variable to the estimated calls/nextDepartures query such that the additional estimated calls fetched adhere to the same filters as the original query. Not sure how much this matters.

feat: add transport mode filter to estimated calls query

---

src/modules/transport-mode/filter/utils.ts

If no filter was set an empty array was passed and no results were returned. Setting all the modes if no filter is in the query, it means that "All" is selected.

fix: fix location bug with transport mode filter

---

src/modules/situations/index.ts
src/modules/situations/situation-message-box.tsx
src/modules/situations/situation-or-notice-icon.tsx
src/modules/situations/situation.module.css
src/modules/situations/types.ts
src/modules/situations/utils.ts
src/page-modules/assistant/server/journey-planner/index.ts
src/page-modules/assistant/server/journey-planner/validators.ts
src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/utils.ts
src/page-modules/departures/__tests__/service-journey-data.fixture.ts
src/page-modules/departures/details/details.module.css
src/page-modules/departures/details/estimated-call-rows.tsx
src/page-modules/departures/details/index.tsx
src/page-modules/departures/details/utils.ts
src/page-modules/departures/server/journey-planner/index.ts
src/page-modules/departures/server/journey-planner/journey-gql/service-journey-with-estimated-calls.gql
src/page-modules/departures/server/journey-planner/validators.ts
src/translations/dictionary.ts
src/translations/index.ts
src/translations/modules/index.ts
src/translations/modules/situation.ts
src/translations/types.ts

This PR features situations and notices on the departure detail page. 
At the time of writing this, one can look up bus 78 from Ringvål and from Lergårdsbakken to test situations. 
Closes https://github.com/AtB-AS/kundevendt/issues/9162
<details>
</details>

feat: situations and notices in departure details

---

src/page-modules/assistant/utils.ts

Currently, a search with a specific search time doesn't work because the trip query parsing fails. This fixes that.

fix: parse trip query

---

src/page-modules/departures/stop-place/stop-place.module.css

This makes it so that the quay header behaves similarly to the app. 
Fixes https://github.com/AtB-AS/kundevendt/issues/15497
Before:
With fix:

fix: quay header

---

src/page-modules/departures/details/estimated-call-rows.tsx
src/page-modules/departures/details/index.tsx

I forgot to add the transport sub-mode to the estimated call row, resulting in the wrong trip decoration line color. 
Fixes https://github.com/AtB-AS/kundevendt/issues/15499

fix: trip decoration line color

---

src/page-modules/departures/details/estimated-call-rows.tsx
src/page-modules/departures/details/utils.ts

This adds the public code to the quay name if defined (P1, 1, etc.). 
Fixes https://github.com/AtB-AS/kundevendt/issues/15506

fix: quay name

---

src/modules/situations/situation-message-box.tsx
src/modules/situations/situation-or-notice-icon.tsx
src/modules/situations/situation.module.css
src/page-modules/departures/__tests__/departure-data.fixture.ts
src/page-modules/departures/__tests__/departure.test.tsx
src/page-modules/departures/nearest-stop-places/index.tsx
src/page-modules/departures/nearest-stop-places/nearest-stop-places.module.css
src/page-modules/departures/server/journey-planner/index.ts
src/page-modules/departures/server/journey-planner/journey-gql/departures.gql
src/page-modules/departures/server/journey-planner/journey-gql/nearest-stop-places.gql
src/page-modules/departures/server/journey-planner/validators.ts
src/page-modules/departures/stop-place/index.tsx
src/page-modules/departures/stop-place/stop-place.module.css
src/translations/pages/departures.ts

This PR adds notices, situations and cancellations for departures. 
At the time of writing this, you can test by looking up Trondheim hovedbrannstasjon and Sluppenvegen, Trondheim. 
<details>
</details>
Closes https://github.com/AtB-AS/kundevendt/issues/9150

feat: notices and situations for departures

---

src/modules/cookies/cookies-context.tsx

To be honest, I'm not sure why this is the case, but the input for this function seems to be a string resulting in `i == true` returning `false`. This is why the dark mode isn't working properly. This fixes that, but it might be a better approach to this. My best guess is that cookies are stored as strings, but then I don't see why this isn't failing in the webshop. 🤷
Fixes https://github.com/AtB-AS/kundevendt/issues/15498

fix: dark mode

---

package.json
src/modules/transport-mode/filter/filter.module.css
src/modules/transport-mode/filter/filter.tsx
src/page-modules/assistant/layout.tsx
src/page-modules/assistant/trip/trip-pattern/trip-pattern.module.css

Text color: `--static-background-background_accent_0-text`
Checked: Background `--static-background-background_0-background`
Unchecked: Border `--static-background-background_0-background`
Hover: Background and border `--static-background-background_1-background`
Focus: Border `--static-status-info-background`
Changed the "More alternatives" button to always mode `interactive_2`. Should revisit this button.

fix: fix colors of transport mode filter

---

src/components/search/search.module.css

fix: no radius for input boxes on safari ios

---

package.json
src/page-modules/assistant/__tests__/assistant.test.tsx
src/page-modules/assistant/details/details.module.css
src/page-modules/assistant/details/index.tsx
src/page-modules/assistant/server/journey-planner/index.ts
src/page-modules/assistant/server/journey-planner/journey-gql/trip-with-details.gql
src/page-modules/assistant/server/journey-planner/validators.ts
src/page-modules/assistant/trip/trip-pattern/__tests__/trip-pattern.fixture.ts
src/page-modules/assistant/trip/trip-pattern/index.tsx
src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/__tests__/trip-pattern.fixture.ts
src/pages/assistant/[id].tsx
src/translations/pages/assistant.ts

This PR introduces a new query for fetching trips with more details, functionality to create a compressed query string that can be used to look up a specific trip, and the base layout for the assistant details page. 
Partially closes https://github.com/AtB-AS/kundevendt/issues/15639

feat: single trip query

---

.prettierrc
README.md
package.json
scripts/build.sh
src/pages/widget/index.tsx
src/widget/vite.config.js
src/widget/widget.ts
yarn.lock

New example of usage:
```
// Ensure that url base is same origin as the page where widget is loaded and the travel planner API
const widget = window.PlannerWeb.createWidget({
urlBase: 'https://reiseplanlegger.example.no/',
});
// After loading JS and CSS file it can be initialized using the following code:
widget.init();
```
This simplifies build and allow us to bundle same asset files to staging and production. Integration strategy remains the same.
Part of https://github.com/AtB-AS/kundevendt/issues/14939

fix: Change widget to init by passing URL to client

---

src/page-modules/assistant/details/details-header/details-header.module.css
src/page-modules/assistant/details/details-header/index.tsx
src/page-modules/assistant/details/details.module.css
src/page-modules/assistant/details/index.tsx
src/page-modules/assistant/server/journey-planner/index.ts
src/page-modules/assistant/server/journey-planner/journey-gql/trip-with-details.gql
src/page-modules/assistant/server/journey-planner/validators.ts
src/translations/pages/assistant.ts

This PR adds the trip details header information. 
Based on https://github.com/AtB-AS/planner-web/pull/85 (awaiting merge)
Partially closes https://github.com/AtB-AS/kundevendt/issues/15639

feat: trip details header

---

src/modules/situations/situation-message-box.tsx
src/modules/situations/situation.module.css

This PR adds the correct text color to the `MessageBox` component. 
Fixes https://github.com/AtB-AS/kundevendt/issues/15671

fix: message box colors for dark mode

---

src/components/map/use-map-legs.ts
src/tests/setup.ts
src/translations/components/map.ts

This PR adds text labels to the start and end points of a trip on the map. I've made the labels look the same as in the app and not the Figma design. Due to technical constraints, it was not feasible to implement the text background as depicted in the Figma designs.
Fixes https://github.com/AtB-AS/kundevendt/issues/9161#issuecomment-1822271071 reported by @HanneLH .

feat: end and start text labels for a trip on the map

---

src/components/loading-empty-results/index.tsx
src/components/message-box/index.tsx
src/components/message-box/message-box.module.css
src/components/search/geolocation-button/index.tsx
src/modules/situations/index.ts
src/modules/situations/situation-message-box.tsx
src/modules/situations/situation.module.css
src/page-modules/assistant/assistant.module.css
src/page-modules/assistant/details/trip-section/index.tsx
src/page-modules/assistant/details/trip-section/interchange-section.tsx
src/page-modules/assistant/details/trip-section/wait-section.tsx
src/page-modules/assistant/layout.tsx
src/page-modules/departures/departures.module.css
src/page-modules/departures/details/index.tsx
src/page-modules/departures/layout.tsx
src/translations/components/empty-search.ts
src/translations/components/geolocation-button.ts

This PR introduces a new feature that improves the user experience by showing an informative error message whenever geolocation services fail or are blocked. It enhances the app's transparency about its operations and guides users to resolve location-based issues.
With this update, we can avoid confusion, assure the user about the application's functionality and increase overall reliability. 
<details><summary>Screenshot</summary>
<p>
</p>
</details> 
Fixes https://github.com/AtB-AS/kundevendt/issues/15347

feat: show error when geolocation fails/is blocked

---

src/components/message-box/index.tsx

Fixes wrong color of icon in light mode.
https://github.com/AtB-AS/kundevendt/issues/15347

fix: set overrideMode for icon in MessageBox

---

src/components/map/map-header.tsx
src/modules/api-server/external-client.ts
src/page-modules/assistant/__tests__/assistant.test.tsx
src/page-modules/assistant/index.ts
src/page-modules/assistant/layout.tsx
src/page-modules/assistant/server/index.ts
src/page-modules/assistant/trip-query-fetcher.ts
src/page-modules/assistant/trip/index.tsx
src/page-modules/assistant/types.ts
src/page-modules/assistant/utils.ts
src/pages/api/assistant/trip.ts
src/pages/assistant/index.tsx

This adds ability to set from and to independently from the URL. It also refactors and simplifies using from/to in the assistant component as to not using state.
Every time we use URL we should use that as a state also. This simplifies things usually, and will make sure the two states doesn't get out of sync.
More URL navigation also shows the slowness of trip API more. Should definitely move trip search to be client side only.
There is still som type mess here and there that I'm not quite happy about. But didn't take the time to fix it here. E.g. Assistant referencing Departure etc.
Things to test out:

feat: support from / to individually from URL

---

src/page-modules/assistant/details/details.module.css
src/page-modules/departures/details/details.module.css

Fixes https://github.com/AtB-AS/kundevendt/issues/15756
The "see in map" button was hard to find on smaller screens. This fixes that by moving it to the top of the page.

fix: move map fullscreen button to top of page

---

src/page-modules/assistant/details/trip-section/wait-section.tsx

The info icon size for short wait was smaller than intended. 
Fixes https://github.com/AtB-AS/kundevendt/issues/15791

fix: info icon size for short wait

---

src/page-modules/departures/__tests__/departure.test.tsx
src/page-modules/departures/fetch-departure-query.ts
src/page-modules/departures/layout.tsx
src/page-modules/departures/nearest-stop-places/index.tsx
src/page-modules/departures/server/index.ts
src/page-modules/departures/types.ts
src/page-modules/departures/utils.ts
src/pages/departures/[[...id]].tsx

Same naming and concept as with assistant to keep it consistent.
Same test plan also.

refactor: make departure state query handling consistant with assistant

---

src/components/search/search.tsx
src/page-modules/departures/client/geocoder/index.ts
src/page-modules/departures/server/geocoder/index.ts
src/pages/api/departures/autocomplete.ts

Use the query parameters `focus.point.lat` and `focus.point.lon` to set a point that the autocomplete search should be based around. I.e. if the focus point is set to Trondheim it is much more likely to get results near Trondheim than e.g. Oslo.
Using the same "settings" the app uses for the weighting, decay function and decay scaling.
- Have not implemented configurable default focus point yet. I think we should plumb Firestore and get configuration from there and then use it for the default point.
- Wanted to use geolocation for the focus point _if_ the user has allowed geolocation previously through the geolocation button, but didn't figure out if it's possible to use the location if it is allowed and not prompt the user.
Closes https://github.com/AtB-AS/kundevendt/issues/15748

feat: use focus point for autocompletion

---

src/page-modules/departures/client/geocoder/index.ts

Some cases happening where it doesn't search due to debounce. ensure revalidate on connect to avoid

fix: revalidation on connect for autocomplete

---

src/components/map/use-map-legs.ts
src/pages/assistant/index.tsx

Show dotted line for foot legs, instead of solid lines, to have the same behaviour as in the app.
<details><summary>Screenshots</summary>
<p>
</p>
</details> 
Fixes https://github.com/AtB-AS/kundevendt/issues/15858

feat: show dotted line for foot legs

---

src/page-modules/assistant/layout.tsx
src/page-modules/departures/layout.tsx
src/translations/pages/assistant.ts
src/translations/pages/departures.ts

I was working on https://github.com/AtB-AS/kundevendt/issues/12072 and had a chat with Christian about this button. The buttons used in the Figma sketches for the planner-web are from the app design-system and we've reused the webshop design-system buttons. 
AtB wants to redo these components to look more the same, but haven't had time to prioritize this. The components are missing states and are therefore hard to implement for now. I tried to implement a new mode, `transparent--bordered`, as a temporary solution, but using the `text-colors-primary` color as a border (as is done for the component in Figma) would give us contrast issues. The button in the travel planner web Figma sketches has overwritten these colors with #FFFFFF which would cause issues elsewhere in the app. 
I personally …

refactor: filter button

---

src/widget/widget.module.css
src/widget/widget.ts

Related to https://github.com/AtB-AS/kundevendt/issues/14939
Adds ability to click to inject from place based on location in browser. Currently not using that as focus point in autocomplete, but this can be added. Will show error if blocked location

feat: adds geolocation to widget

---

src/components/line-chip/index.tsx
src/components/line-chip/line-chip.module.css
src/components/search/search.tsx
src/components/venue-icon/index.tsx
src/page-modules/assistant/details/trip-section/interchange-section.tsx
src/page-modules/assistant/details/utils.ts
src/page-modules/assistant/server/journey-planner/validators.ts
src/page-modules/departures/nearest-stop-places/index.tsx
src/page-modules/departures/server/journey-planner/index.ts
src/page-modules/departures/server/journey-planner/journey-gql/nearest-stop-places.gql
src/page-modules/departures/server/journey-planner/validators.ts

This PR introduces a significant feature enhancement to our application. Specifically, it extends the functionality to show all modes of transport available for a given stop place.
Prior to this update, our application may not have provided comprehensive transport mode information for each stop place, limiting its overall utility for end-users. With the implementation of this feature, we can now present complete and valuable information on all transport modes for any given stop place, thereby significantly improving the user experience.
The code modifications encompassed by this commit include updates to both the display logic and the data handling components of our application. These changes ensure that our system can retrieve, process, and render all transport mode data associated with …

feat: show all transport modes for a stop place

---

src/modules/transport-mode/filter/__tests__/filter.test.tsx
src/modules/transport-mode/filter/filter.tsx

This changes the behavior of the transport mode filter so that when "All" is selected and the user clicks another transport mode, only the selected transport mode is selected. 
Closes https://github.com/AtB-AS/kundevendt/issues/15923

refactor: transport mode filter behavior

---

src/page-modules/assistant/__tests__/assistant-data.fixture.ts
src/page-modules/assistant/non-transit-pill/index.tsx
src/page-modules/assistant/server/journey-planner/index.ts
src/page-modules/assistant/server/journey-planner/journey-gql/trip.gql
src/page-modules/assistant/server/journey-planner/validators.ts

This PR introduces a new feature that expands the functionality of our trip information display. Previously, our system only provided specific details for transit-based trips. Now, with this update, users can also access detailed information for non-transit trips. This includes details about the trip's origin, destination, duration, distance, and path. This improvement aims to offer a more comprehensive and convenient experience for users, allowing them to effectively plan their trips regardless of the transportation mode.
<details><summary>Screenshots</summary>
<p>
</p>
</details> 
Closes https://github.com/AtB-AS/kundevendt/issues/15873

feat: show details for a non-transit trip

---

src/components/map/map.module.css
src/components/map/map.tsx
src/tests/setup.ts

Disables map if the browser doesn't support WebGL. These are old browsers. Acceptable to not show map if this happens

fix: avoid crashing details if browser not supports webgl

---

src/page-modules/assistant/details/details-header/index.tsx
src/page-modules/assistant/details/index.tsx
src/page-modules/assistant/details/trip-section/index.tsx
src/page-modules/assistant/server/journey-planner/index.ts
src/page-modules/assistant/server/journey-planner/journey-gql/trip-with-details.gql
src/page-modules/assistant/server/journey-planner/journey-gql/trip.gql
src/page-modules/assistant/server/journey-planner/validators.ts
src/page-modules/assistant/trip/trip-pattern/__tests__/trip-pattern.fixture.ts
src/page-modules/assistant/trip/trip-pattern/index.tsx
src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/__tests__/trip-pattern.fixture.ts
src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/index.tsx
src/page-modules/assistant/trip/trip-pattern/utils.ts
src/utils/date.ts

Show correct trip duration based on rounded times. Previously the trip duration did not always correspond with the formatted times of departure and arrival. E.g. if a trip departs at 16:04 and arrives at 16:48, the duration might have said 42 minutes since the departure time rounds down (floors) and arrival times are rounded up (ceil)¹. 
So the solution was to base the duration of the trip on the formatted times of departure and arrival, ignoring the real duration of the trip. That way we get a duration corresponding with the times shown.
[1]: AtB have spent deciding how to round the departure and arrival times in the app, so that should be done the same in the travel planner; "We have chosen to display rounding that minimizes the likelihood of the user missing the bus - so departures are …

fix: show correct trip duration based on rounded times

---

src/translations/common/layout.ts

Updated the meta description to not be "AtB desc" any more.
The current text is most likely temporary. Have asked Christoffer in FRAM what the text should be.
Closes https://github.com/AtB-AS/kundevendt/issues/15929

fix: update meta description

---

src/components/map/map.module.css

This PR addresses style adjustments specifically for small screens by removing the border-radius of the map. 
-   Implementation of a media query to target small screen devices.
-   Removal of `border-radius` property from the map on small screen devices.
**Impact**: This change enhances the user experience on mobile devices, improving visibility and interaction with the map.
Closes https://github.com/AtB-AS/kundevendt/issues/16001

style: remove border-radius of map on small screens

---

src/modules/transport-mode/icon/index.tsx
src/modules/transport-mode/index.ts
src/modules/transport-mode/utils.ts
src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/__tests__/trip-pattern-header.test.tsx
src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/index.tsx
src/translations/pages/assistant.ts

This PR fixes a mislabeling issue, ensuring the correct information is shown for transportation mode.
-  Updated logic to correctly display "Ferry from" when the transportation mode is a ferry, not a boat.
**Impact**: This change improves the display information integrity, enhancing user understanding and experience.
Closes https://github.com/AtB-AS/kundevendt/issues/15996

fix: show "Ferry from" if it's ferry and not boat

---

src/page-modules/assistant/layout.tsx

Use the point in "From" as focus point when searching for address, pier or stop place in "To". 
The property was removed at some point and the only thing needed was to add it again.

fix: use point in "From" as focus point

---

src/translations/pages/assistant.ts
src/translations/pages/departures.ts

Christoffer reported that we use `quay` and not `pier` so I have changed this

refactor: use quay instead of pier

---

src/page-modules/departures/server/journey-planner/utils.ts

This fixes so quays with no departures are placed at the back of the list. 
Fixes issue found by @tormoseng https://github.com/AtB-AS/kundevendt/issues/15894#issuecomment-1855677167

fix: quay sorting

---

src/components/map/map.tsx
src/page-modules/departures/nearest-stop-places/index.tsx
src/page-modules/departures/stop-place/index.tsx

Now the order when navigating with keyboard is off. Using grid here however we can just reorder the HTML to make it better. Also added aria-hidden to map as it doesn't make sense for screen readers.

fix: keyboard navigation order with map

---

src/page-modules/departures/client/journey-planner/index.ts
src/page-modules/departures/server/journey-planner/index.ts
src/page-modules/departures/server/journey-planner/journey-gql/estimated-calls.gql
src/page-modules/departures/stop-place/index.tsx
src/pages/api/departures/journey-planner.ts

This PR fixes an issue where the website crashes on loading the next departures. This was because of some removed properties and newly added ones that were not mapped from GraphQL. 
The functionality is still not optimal and won't return new departures in some cases. I'll look into handling this as well, but this fixes the crashing at least.

fix: add correct data to estimated calls for next departures

---

src/components/button/button.module.css
src/components/button/utils.tsx
src/page-modules/assistant/layout.tsx
src/page-modules/departures/layout.tsx
src/widget/widget.module.css

Add bordered mode of interactive 0 button.

fix: add bordered mode of interactive 0 button

---

.gitignore
package.json
src/page-modules/departures/stop-place/index.tsx
src/page-modules/departures/stop-place/stop-place.module.css
yarn.lock

Closes https://github.com/AtB-AS/kundevendt/issues/15983
Chore to make the view of cancelled departures more similar to the view in the app described in this pull request: https://github.com/AtB-AS/kundevendt/issues/15925  
<details>
Not cancelled / Cancelled
</details>

feat: make the view of cancelled departures appear more similar as in the app

---

src/components/search/search.module.css
src/page-modules/assistant/assistant.module.css
src/page-modules/departures/departures.module.css

Add a focus style to the search input that is more in line with the focus styles of the surrounding components.

style: add focus style to search input

---

src/page-modules/departures/stop-place/index.tsx
src/page-modules/departures/stop-place/stop-place.module.css

Instead of using a `Link` I changed it to a `button` that calls `router.reload()`. This reloads the page and results in reloading the estimated calls list.
I think this is by no means a permanent solution, but rather a temporary solution to the problem we are currently seeing. At a later point we could look into updating just the list and not the whole page, but then we would be fetching data on the client side rather than the server side.
,> [!NOTE]
> I think the `Link` might be working, but if a quay, or multiple, is collapsed it won't be visible that the estimated calls was updated.

fix: reload page manually to refresh estimated calls

---

src/components/loading-empty-results/index.tsx
src/page-modules/assistant/layout.tsx

Currently, when both from and to are empty and a place is selected the searching illustration and loading mode of the button is briefly triggered. I think this can cause confusion for some users, seeing that something happened on the screen, but in fact nothing did other than updating the URL (since nothing is done if either from or to is empty when the page loads).
Related to https://github.com/AtB-AS/kundevendt/issues/15757

fix: only show loading when both to and from are selected

---

orgs/atb.json
orgs/fram.json
orgs/nfk.json
orgs/schema-validation.json
src/layouts/shared/page-header.module.css
src/modules/org-data/index.tsx
src/page-modules/assistant/assistant.module.css
src/page-modules/assistant/layout.tsx
src/page-modules/departures/departures.module.css
src/page-modules/departures/layout.tsx
src/translations/pages/assistant.ts
src/translations/pages/departures.ts

As per the Product Owner's request, I have included a new link enabling users to navigate back to the home page of each organization. This adjustment aligns with the Figma sketches. Additionally, I have modified the page header to span the full width, mirroring the design in the Figma sketches.
Edit: I've updated the back link title to include the name of the home page (e.g. frammr.no, atb.no). 
<details>
**Figma**
**New website**
</details>

feat: link to home page

---

.github/workflows/docker.yml

The current firebase app ID is for the webshop which does not have analytics enabled. The new app ID is for the planner web app that has it enabled. 
https://github.com/AtB-AS/kundevendt/issues/15995

fix: add correct firebase app ID to FRAM prod

---

src/pages/departures/[[...id]].tsx

Currently, the widget sends the users to `/departures?id=SomeId&searchMode=now` instead of `/departures/SomeId?searchMode=now`. To handle this I've set up a redirect until we have made a release of the widget.

temp: redirect departures

---

src/page-modules/assistant/server/journey-planner/index.ts
src/page-modules/assistant/server/journey-planner/journey-gql/trip.gql

Currently, the parameter to use for limiting walking is set to 1.5, which we thought was the default for the app. It turns out the default is 5 and Entur uses 4. With the current config (1.5) we have had reports that some transfers are missing, such as when traveling from Kristiansund to Molde Sjukehus. This change fixes that, so that line 702 is suggested instead of walking (see screenshots).
I've also added the transferSlack configuration, in line with what the app uses now and what the PO wanted. 
Closes https://github.com/AtB-AS/kundevendt/issues/15500
**Before**
**Now**

fix: trip query transferSlack and walkReluctance config

---

src/page-modules/assistant/trip/trip-pattern/index.tsx
src/page-modules/assistant/trip/trip-pattern/trip-pattern.module.css

The search results currently only show the expected start time, but they should show both aimed (striked-through) and expected.
<details>
<summary>screenshot</summary>
</details>
For all delayed departures, display both the expectedStartTime and the aimedStartTime (strike-through). Other departures that are on time only displays expectedStartTime, as for these departures expectedStartTime === aimedStartTime.

feat: display both aimed start time and expected start time of departure in case of delay. 

---

src/modules/cookies/index.tsx
src/page-modules/assistant/details/trip-section/estimated-calls-section.tsx
src/page-modules/assistant/details/trip-section/index.tsx
src/page-modules/assistant/details/trip-section/trip-section.module.css
src/page-modules/assistant/server/journey-planner/index.ts
src/page-modules/assistant/server/journey-planner/journey-gql/trip-with-details.gql
src/page-modules/assistant/server/journey-planner/validators.ts
src/page-modules/departures/details/index.tsx
src/translations/pages/departures.ts

This PR adds the functionality to see details about the intermediate stops of a service journey from a trip pattern. 
I've added the headers referer to the global data so that we have the correct back link in the departures details page. If a user navigates to the departures details page from a trip suggestion one should be redirected back to the trip suggestion. In other cases (from departures or opening the link from someone) one should be navigated to the departures page. 
Closes https://github.com/AtB-AS/kundevendt/issues/15872

feat: link to service journey details from a trip suggestion

---

orgs/fram.json

We are currently using the webshop accessibility statement for the planner web. PO wants to use the one from frammr.no instead.

fix: update accessibility statement url for FRAM

---

src/page-modules/departures/stop-place/index.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/16110
Received feedback that it says "Now" on all departures when you search for previous departures backwards in time.
<details>
<summary>screenrecording</summary>
https://github.com/AtB-AS/planner-web/assets/59939294/82cdc9cc-0305-42a2-8db4-8824ba72b7a1
</details>
Whenever searching after past departures, the start times that were expected for each departure is displayed.

fix: display the departure time that was expected when searching after past departures

---

src/modules/cookies/index.tsx
src/page-modules/assistant/details/index.tsx
src/page-modules/assistant/details/trip-section/estimated-calls-section.tsx
src/page-modules/assistant/details/trip-section/index.tsx
src/page-modules/assistant/details/trip-section/trip-section.module.css
src/page-modules/assistant/details/utils.ts
src/page-modules/assistant/server/journey-planner/index.ts
src/page-modules/assistant/server/journey-planner/journey-gql/trip-with-details.gql
src/page-modules/assistant/server/journey-planner/validators.ts
src/page-modules/departures/details/index.tsx
src/translations/pages/departures.ts

This PR adds the functionality to see details about the intermediate stops of a service journey from a trip pattern.
I've added the headers referer to the global data so that we have the correct back link in the departures details page. If a user navigates to the departures details page from a trip suggestion one should be redirected back to the trip suggestion. In other cases (from departures or opening the link from someone) one should be navigated to the departures page.
I also extended the compressed query string so that the user can navigate back to the trip search results with the correct search parameters.
Closes https://github.com/AtB-AS/kundevendt/issues/15872

feat: intermediate stops link from trip details

---

src/modules/transport-mode/icon/icon.module.css
src/page-modules/assistant/trip/trip-pattern/index.tsx
src/page-modules/assistant/trip/trip-pattern/trip-pattern.module.css

Fixes https://github.com/AtB-AS/kundevendt/issues/16000
We received feedback that the boxes that do not contain a transport icon and route number did not adjust in width according to the text below the box.
<details>
</details>
prior fix / after fix / after fix three_digit_route
Fix box styling to ensure that box containing both the icon and route number is at least as wide or wider than the aimed start time + the expected start time.

fix: ensure that the icon box is as wide or wider than the departure time bellow the box 

---

src/page-modules/departures/details/index.tsx

Fixes https://github.com/AtB-AS/kundevendt/issues/15983
Currently, both the live icon and the description "I rute" is displayed when routes are cancelled in realtime. When cancelled, neither th icon or the description should be displayed. 
<details>
<summary>screenshot</summary>
</details>
Added a condition to verify that the departure is not cancelled. If cancelled, the icon and description are not included.

fix: ensure that live icon and description is not rendered when displaying canceled departures.

---

src/modules/firebase/default-focus-point.ts
src/modules/firebase/types.ts
src/page-modules/departures/server/geocoder/index.ts

This PR adds functionality that fetches the default focus point from Firebase and uses it for autocomplete, if it exists. If it does not exist in Firebase, a fallback is used. This fallback is currently hardcoded, not sure if we should handle it a different way. If we do, it means we have several ways of configuring the default focus point, which I mean is unnecessary. I think it's fine to have a hardcoded fallback, to e.g. Trondheim as it is now, and if it's needed/wanted to have it somewhere else Firebase should be used.
Fixes https://github.com/AtB-AS/kundevendt/issues/15997

feat: get default focus point from Firebase

---

src/widget/widget.module.css
src/widget/widget.ts

This PR introduces a couple of features and bug fixes:
-  **Features:**
- Added functionality to reset search when switching between tabs.
- Make it possible to click the search button at all times, routing to the travel planner even though from/to might not be set. Some users experienced trouble showing the autocomplete box, and wasn't able to click the search button because they couldn't set a location.
-  **Fixes:**
- Fixed proper use of ARIA property.
- Added missing translation for "From" label.
~~*This PR addresses the issue with the widget failing due to being nested within a `form` element in the FRAM page. The problem arises from the HTML specification restriction of not allowing a form inside another form.*~~
~~*1. The widget has been rewritten to remove the `form` dependency. …

feat: reset search when switching tab

---

src/components/button/button.tsx
src/components/message-box/index.tsx

Fixes https://github.com/AtB-AS/kundevendt/issues/15810
When the voiceover reads message boxes, only the button text is read. It is desirable that both the message and the button text is read by the voiceover.  
<details>
<summary>screenrecording</summary>
https://github.com/AtB-AS/planner-web/assets/59939294/7be3d20b-4f43-4845-81ac-a05bae115605
</details>
The proposed solution passes the message as prop to the button component, where it is included in the buttons arial-label, which is read by the voiceover.

fix: includes message from message box into buttons aria-label, to make message accessible for voiceover.

---

src/components/map/map.tsx
src/components/map/utils.ts
src/page-modules/assistant/details/index.tsx

This PR makes the whole trip visible on the map on load instead of the first stop place. 
Closes https://github.com/AtB-AS/kundevendt/issues/16058

fix: show whole trip on map load

---

package.json
patches/@github+combobox-nav+2.3.0.patch
src/widget/widget.ts
yarn.lock

The issue with the widget not selecting a place was due to the event listener on blur. The blur event was happening before the "combobox-commit" event which is the one that sets the place. A fix for this was to add event listener to the `mousedown` event instead of the `click` event in the combobox code. That was solved with a patch using `patch-package`. Also mentioned in this issue: https://github.com/github/combobox-nav/issues/54
Also fixed an issue that showed "undefined" if selected place did not have a locality.

fix: fix issue with widget not selecting place

---

src/components/map/use-map-legs.ts
src/components/map/use-map-tariff-zones.ts
src/components/map/utils.ts
src/page-modules/assistant/server/journey-planner/index.ts
src/page-modules/assistant/server/journey-planner/journey-gql/trip-with-details.gql

This ensures that the trip and trip with details query use the same configuration. Before this, we could not view the details of some of the travel suggestions, because we couldn't retrieve the same suggestions again. 
Edit: test cases can be found in the issue
I also experienced a bug with the map when testing this fix, where it tried to draw the same route multiple times. To fix this I added a check to see if it is already drawn or not, before trying to add it. 
Fixes https://github.com/AtB-AS/kundevendt/issues/16414

fix: assistant details page not loading travel suggestion

---

src/modules/transport-mode/filter/__tests__/filter.test.tsx
src/modules/transport-mode/filter/filter.tsx
src/page-modules/assistant/layout.tsx
src/page-modules/assistant/utils.ts

Added a debounce to the function that updates the URL (performing a search) so that a search is not performed immediately after changing a filter, but after a set time. I set this time to be 500ms. In addition, with the debounce the function is not called for every single filter change, but only the last change within the last 500ms.
Closes https://github.com/AtB-AS/kundevendt/issues/16003

feat: debounce search when filter change

---

src/widget/widget.ts

Received feedback that role=combobox is used as an attribute in several html elements. That attribute is only required in an input element 
<details>
</details>
Before / after
Remove role=combobox from all elements other than input.

fix:  remove duplicate comboboxes. 

---

src/components/map/map.tsx

The map does not show the correct position on the departure page when searching for an address or a stop place. This was because the type required an initial zoom level, which is not necessary. I've updated the code so that this can be undefined. 
Fixes https://github.com/AtB-AS/kundevendt/issues/16571

fix: map not rendering the correct position on the departure page

---

public/widget/GYJwhgtkA/2.8.0/planner-web.mjs
public/widget/GYJwhgtkA/2.8.0/planner-web.umd.js
src/modules/search-time/selector/index.tsx
src/widget/widget.ts

Closes https://github.com/AtB-AS/kundevendt/issues/16349
Received feedback that the screen reader was unable to read the search time radio buttons, due the attribute specification: 'aria-hidden:true'. 
Remove the attribute specification: 'aria-hidden:true'.

fix: make aria-labels in the search time selector visible to the screen reader

---

orgs/atb.json
orgs/fram.json
orgs/nfk.json
orgs/schema-validation.json
src/layouts/shared/footer.tsx
src/modules/org-data/index.tsx
src/translations/modules/layout.ts

This adds a link to ticket prices in the footer for FRAM, NFK and AtB.
Closes https://github.com/AtB-AS/kundevendt/issues/16680

feat: ticket information url in footer

---

src/components/search/search.module.css
src/widget/widget.module.css

Closes https://github.com/AtB-AS/kundevendt/issues/16358
Received feedback that the contrast between the placeholder text and the background was too weak.
<details>
<summary>screenshots/video/figm</summary>
</details>
- The colour contrast ratio should minimum be at  4.5:1.

fix: increase the contrast between placeholder text and the background  

---

orgs/atb.json

Update the query parameters for trip search to be equal as in the AtB app. The changes are as the default parameters from Entur. See also [Slack](https://mittatb.slack.com/archives/CHLDG8C30/p1706776408713929).
Maybe we should change the values, but this takes a bit of testing, and for now it's better to have the values equal.
<details>
<summary>From Shamash</summary>
</details>

Update trip parameters for AtB

---

orgs/fram.json
orgs/nfk.json

The current values that are used are Entur default values. This updates the values to be the same as in the app. 
Closes https://github.com/orgs/AtB-AS/projects/10/views/13?pane=issue&itemId=49668512 for FRAM and NFK.

fix: journey planner API config for FRAM and NFK

---

.github/workflows/playwright-scheduled-staging.yml
.github/workflows/playwright.yml
.gitignore
e2e-tests/search-test.spec.ts
package.json
playwright.config.ts
src/page-modules/assistant/trip/trip-pattern/index.tsx
vitest.config.ts
yarn.lock

Adds initial structure for running E2E tests on pull requests and all staging environments every 3 hours. At some point this could also be extended to running as smoke tests for the production environment.
Currently only includes one test, but want to merge this before adding more test cases
Part of https://github.com/AtB-AS/kundevendt/issues/16713

chore: adds initial e2e case

---

src/components/search/search.tsx
src/page-modules/departures/server/geocoder/index.ts
src/page-modules/departures/types.ts

Closes https://github.com/AtB-AS/kundevendt/issues/16688
When clicking on the Ålesund geopoint in travel planner web, the locality attribute  was undefined in the input box.
This is probably due to missing municipality field in OSM. 
How to replicate:
Enter Ålesund in input. Click geopoint at top. See undefined in input box. If running locally, the application may crash. 
<details>
<Summary>screenshots/problem</Summary>
</details>
<details>
<Summary>screenshot/solution</Summary>
</details>
- Set locality to null if noe defined
- Only display search locality if not it is defined."

fix: filter out locations where locality is undefined from the travel planner's input field.

---

src/page-modules/assistant/server/journey-planner/journey-gql/trip-with-details.gql

Currently, one cannot open the details page for a trip suggestion, which can only be found when searching with a line filter. This is because the trip details query doesn't consider the line filter, and therefore can't find the trip suggestion. 
Fixes https://github.com/AtB-AS/kundevendt/issues/17059

fix: details page for trip search with line filter

---

src/modules/search-time/selector/index.tsx

When reselecting the current the year twice, the date is automatically set to current date. At the moment,  this is not the case when reselecting the current month twice. To make the user flow as predictable as possible, this function should be the same for both year selection and month selection     
Update to automatically rest to current date if reselecting the current month or current year twice.

fix: automatically resets to the current date if the current month or current year is reselected twice.

---

src/modules/transport-mode/filter/__tests__/filter.test.tsx
src/modules/transport-mode/filter/filter.tsx
src/page-modules/assistant/layout.tsx

Temporary solution for task https://github.com/orgs/AtB-AS/projects/10/views/13?pane=issue&itemId=51482158
NFK have requested that flights are not part of the default transport methods in travel planner web. It should still be possible to enable for the users, but not selected as default.
This is default also in app and at Entur.
<details>
<summary>screenshot</summary>
</details>
Disabling the travel planner flight filter for for all organisations until a more sophisticated solution where each organisation can configure filter preferences.

feat: disable travel planner flight filter by default 

---

src/components/button/button.module.css
src/widget/vite.config.js
src/widget/widget.module.css
src/widget/widget.ts

Closes https://github.com/AtB-AS/kundevendt/issues/16996
Currently, the widget search button and the travel planner search button have dissimilar appearance when FRAM is the organisation. These buttons should have the same appearance.  
<details>
https://github.com/AtB-AS/planner-web/assets/59939294/ef5d2679-709b-4b78-9528-85cec452275d
https://github.com/AtB-AS/planner-web/assets/59939294/7204ecb0-dc9e-4ba3-a374-01a70f75ba4f
</details>
Style the widget search button the same way as the search button currently implemented in the travel planner.

fix: update button style in widget to match button in travel planner when fram is the organization.  

---

.github/workflows/playwright.yml

Changes playwright to trigger on deployment state.
Makes it more stable when running on PR

chore: trigger playwright on deployment state

---

src/widget/widget.module.css
src/widget/widget.ts

Closes https://github.com/AtB-AS/kundevendt/issues/17110
-  When nfk is set as the organization, the width of the search button is too wide. 
-  The text colour of the active tab is set to black. The colour should be withe, as in the travel planner on web.  should.
- The selected tab should have bold font, as in the travel planner on web.   
<details>
Before / after
- Fix the mentioned bullet points.

fix: improve minor styling errors in widget

---

src/pages/api/departures/autocomplete.ts

Reis uses https://www.reisnordland.com/ when English is the selected language. To make the widget work we have to allow https://www.reisnordland.com/ as well

fix: add allow url for CORS reisnordland com

---

src/components/search/search.module.css

Closes https://github.com/AtB-AS/kundevendt/issues/17176
The placeholders and selected from/to destinations are cut off when the width of the screen is reduced to be slightly wider than mobile view. This is against requirement [1.4.12 - Text Spacing](https://www.uutilsynet.no/wcag-standarden/1412-tekstavstand-niva-aa/146), in the WCAG standard.
<details>
https://github.com/AtB-AS/planner-web/assets/59939294/ae503c6e-0320-44db-9c1f-c9c50087c8b6
</details>
Adjust to mobile view earlier before the placeholders are cut of off due too narrow window width.

fix: update search component to not cut placeholder early

---

src/layouts/shared/footer.tsx
src/page-modules/assistant/layout.tsx
src/page-modules/departures/layout.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/17181
Closes https://github.com/AtB-AS/kundevendt/issues/17198
The headings in the DeparturesLayout are using the p-tags instead of h-tags. In addition, some headers break the requirement for correct use of h-tags in sequentially descending order.
- Update code to use h-tags instead of p-tags.

fix: update the header elements to achieve a correct sequentially-descending order 

---

src/modules/search-time/selector/selector.module.css

Fixing issue with default values when integrating widget.
Before:
After

fix(widget): set correct line height

---

src/components/map/index.tsx
src/components/map/map-with-header.tsx
src/components/map/map.tsx

The current standalone build includes `map.tsx` which gives a type error (missing imports). To fix this we can use `export default` for the Map component.
Closes https://github.com/AtB-AS/kundevendt/issues/17228

fix: build with dynamic import of map

---

src/components/map/map.tsx
src/components/search/geolocation-button/index.tsx
src/widget/widget.ts

Fixes issue with wrong icon for GeoLocation button 😳 Has been working before now as places/City has been wrong, but this has since been fixed in https://github.com/AtB-AS/design-system/pull/164
Before:
Now:

fix: fixes wrong icon for GeoLocation button

---

.github/workflows/docker.yml

Removes empty lines from docker.yml. EMpty lines were added in the last PR, making the build script fail.

fix: remove empty lines from build script

---

src/modules/search-time/selector/__tests__/selector.test.tsx
src/modules/search-time/selector/index.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/17561
Match the behavior of the app with the departure filter time. Should be possible to see results back in time (two days). This changes from existing behavior where it is only allowed for 1 day.
Screenshots were the 9th of April.
<details>
</details>
Expand the search time selector to enable retrieval of search results from yesterday.

feat: expand the search time selector to enable retrieval of search results from yesterday.

---

src/layouts/base/index.tsx
src/pages/api/departures/og-location.tsx

Fixes the color of the header on iOS Safari to match the color of the header it self. Making it look a bit more intentional.

fix: theme color to match header for iOS safari

---

.gitignore
package.json
src/modules/transport-mode/filter/__tests__/filter.fixture.ts
src/page-modules/assistant/__tests__/set-transport-mode-filters.test.ts
src/page-modules/assistant/layout.tsx
src/page-modules/assistant/utils.ts
yarn.lock

Closes https://github.com/AtB-AS/kundevendt/issues/17912
FRAM and NFK have requested that some transport mode filters should be unchecked by default in both app and travel planner web. This request highlights a need that we need to address. As the number of organizations in the OMS grows, it becomes increasingly more difficult to find on singel transport mode configuration that will work well for all orgnaizations. Therefore, each organization should be able to configure their own desired default transportModes. 
The requests from AtB, FRAM and NFK are as following:
<details>
**NFK**
**FRAM**
**AtB**
</details>

feat: extend travel mode filter selection to use selected_as_default property

---

src/page-modules/assistant/details/index.tsx
src/translations/pages/assistant.ts

Closes https://github.com/AtB-AS/kundevendt/issues/18065
As mentioned in the conversation, the same note informing the users out the need to buy tickets from other sources than in the app, should also be shown in the planner web.
> The booking phone number and/or URL is only shown if the booking status is "bookable", see https://github.com/AtB-AS/planner-web/blob/main/src/page-modules/assistant/details/trip-section/booking-section.tsx#L57. 
> 
> This is the same as what the app does. However, the app also has a note saying "This journey requires a ticket that is not available from this app, or must be purchased from a provider other than AtB." This doesn't answer all of the questions a customer might have, but it's some more information. A better approach could be to show the booking URL …

feat: add note informing users about having to buy external ticket

---

src/pages/widget/index.tsx
src/widget/widget.module.css
src/widget/widget.ts

Added options to enforce use of inherited font for all elements in the widget. Will allow for parent container to dictate the use of font family. If not specified, the default behaviour is to use Roboto which is the default font for the hosted planner web solution (and webshop).
```ts
const widget = window.PlannerWeb.createWidget({
urlBase: 'https://reiseplanlegger.example.no/',
language: 'nn', // supports 'nb', 'nn' and 'en'
// Optional options
outputOverrideOptions: {
// Inherit font from page website.
// By default it uses Roboto as the hosted planner web solution.
inheritFont: false,
},
});
```
Fixes https://github.com/AtB-AS/kundevendt/issues/18111

feat(widget): adds option to use inherited font in the widget

---

src/pages/widget/index.tsx
src/widget/widget.module.css
src/widget/widget.ts

Closes https://github.com/AtB-AS/kundevendt/issues/18000
Add the ability to choose a single column type design (enforce mobile view) for the widget.
This is a need sent in by Troms.
<details>
</details>
Include `singleColumnLayout` as an optional property to determine whether the widget should be shown in single column layout or not. By default set to false.

feat: extend widget with optional single column layout

---

src/modules/global-messages/converters.ts
src/modules/global-messages/types.ts

With this PR we start using zod for parsing global messages. I've also updated the `startDate` and `endDate` type to be Date instead of Firestore Timestamp. 
Part of solving https://github.com/AtB-AS/kundevendt/issues/17725

refactor: parse global messages using zod

---

src/layouts/shared/page-header.tsx
src/translations/common/layout.ts

After user testing it was hard to find way back even with link. This is quick test/fix to improve that but, long term issue is located at: https://github.com/AtB-AS/kundevendt/issues/18376

fix: let header image navigate to main page

---

.github/workflows/docker.yml
orgs/troms.json
package.json
src/translations/common/titles.ts
src/translations/modules/layout.ts
yarn.lock

This PR does 3 things:
1. Add troms-prod firebase configuration
2. Refactor to use the Svipper name
3. Upgrades the assets and theme packages with the latest Svipper changes
There are some issues with the colors and missing illustrations, but after merging this it will be easier for the PO and designer to locate what's missing or need refactoring. 
Partially closes https://github.com/AtB-AS/kundevendt/issues/18397

feat: troms configuration

---

src/page-modules/assistant/layout.tsx

Removing the `useEffect` caused the code to run on the server side, causing an error by `next/router` which can only be run on the client side.

fix: fix server side redirect error

---

src/components/message-box/message-box.module.css

According to the design in Figma, the message box border should be 2px and not 1px.

style: make the message box border 2px

---

src/page-modules/assistant/details/trip-section/index.tsx
src/page-modules/assistant/details/trip-section/interchange-section.tsx
src/page-modules/assistant/server/journey-planner/index.ts
src/page-modules/assistant/server/journey-planner/journey-gql/trip-with-details.gql
src/page-modules/assistant/server/journey-planner/journey-gql/via-trip-with-details.gql
src/page-modules/assistant/server/journey-planner/validators.ts
src/translations/pages/assistant.ts

Fixes https://github.com/AtB-AS/kundevendt/issues/18410
I'm unsure whether or not to actually handle the null case or just treat it as 0. But for now, if the max wait time is 0 we just treat it as not defined. 🤔 Open to actually handle it explicitly though.

feat: adds maximum interchange wait time to details page. Fixes #18410

---

src/page-modules/assistant/trip/index.tsx

For some trips, when the previous page has an empty trip pattern list, the day label is wrong (see screenshot). This PR updates the `getPreviousDepartureTime` function to take that into account and fix this bug. 
<details>
**Before**
**After**
</details>

fix: show correct day label for trip results

---

package.json
src/components/tab-link/tab-link.module.css
src/modules/transport-mode/filter/filter.module.css
yarn.lock

Changing the text color on hover from background accent **0** to background accent **1** is not optimal in my opinion, so I changed it to lower the opacity on hover instead. This avoids the text changing from white to black on hover. 
The opacity for the "infoText" was a bit low so I changed that to 0.75 instead of 0.6. 
Closes https://github.com/AtB-AS/kundevendt/issues/18512

chore: upgrade theme and assets packages

---

src/layouts/shared/footer.module.css
src/layouts/shared/footer.tsx

Troms won't have social media links or a logo in the footer, so I made some CSS changes to the bottom links so that:
- Center the element if we have one element
- Use space-evenly if we have two elements
- Use space-between if we have three or more elements
(same behavior as in the webshop https://github.com/AtB-AS/webshop2/pull/454)

fix: bottom links layout in the footer

---

src/page-modules/assistant/details/trip-section/index.tsx
src/page-modules/assistant/details/trip-section/interchange-section.tsx
src/page-modules/assistant/server/journey-planner/index.ts
src/page-modules/assistant/server/journey-planner/journey-gql/trip-with-details.gql
src/page-modules/assistant/server/journey-planner/journey-gql/trip.gql
src/page-modules/assistant/server/journey-planner/journey-gql/via-trip-with-details.gql
src/page-modules/assistant/server/journey-planner/validators.ts
src/page-modules/assistant/trip/trip-pattern/index.tsx
src/translations/pages/assistant.ts

Closes https://github.com/AtB-AS/kundevendt/issues/18588
Currently, the way a bus line change a during a trip is displayed as there is also conducted a bus change. This can be confusing and might lead to customers to get of the bus when thei are supposed to stay seated.
Entur displays this differently, where only the waiting time is stated in the stop details so that there is no misunderstanding among customers who might jump off and wait for the next bus
<details>
<summary>screenshots/trip</summary>
Planner Web currently:
Entur:
After this PR:
</details>
<details>
<summary>screenshots/trip-details-view</summary>
Planner Web currently:
Entur:
After this PR:
</details>
Extend trip schema with with the property staySeated to check whether passengers should stay seated or not during …

fix: add condition to check whether passengers should stay seated between leg interchanges.   

---

src/utils/date.ts

Closes https://github.com/AtB-AS/kundevendt/issues/18697
When in another timezone, departures from a stop place are displayed in local time instead of in CET. These departures should always be displayed in CET. 
- Change the local timezone on your computer.
- Search after a stop place in departures. 
<details>
<Summary>screenshots/vid
eo</Summary>
</details>
<details>
<Summary>screenshots/video</Summary>
</details>
Update formatToClockOrRelativeMinutes to take time zone of user into account.

fix: display departures in CET instead of local time 

---

orgs/troms.json

The Svipper brand is now live and this updates the current fylkestrafikk- to svipper-links.
Closes https://github.com/AtB-AS/kundevendt/issues/18397

fix: add svipper links

---

src/page-modules/assistant/server/journey-planner/index.ts
src/page-modules/assistant/server/journey-planner/journey-gql/trip-with-details.gql
src/page-modules/assistant/server/journey-planner/journey-gql/via-trip-with-details.gql
src/page-modules/assistant/server/journey-planner/validators.ts

Closes https://github.com/AtB-AS/kundevendt/issues/4203
It seems that the app is currently not handling notices on the EstimatedCall on which a trip ends: https://github.com/AtB-AS/mittatb-app/blob/51ea34a7b69f8aca381aac5ffc94fa36a88086ae/src/travel-details-screens/utils.ts#L44-L50
<details>
</details>
To solve, we should probably extend the code above to also include notices from ToEstimatedCall.

feat: extend notices to inform users about the need to contact the relevant authorities to carry out certain trips

---

src/components/map/map.tsx
src/components/map/use-fullscreen-map.ts
src/layouts/shared/menu-utils.tsx
src/utils/user-media-query.ts

While looking into the excessive Mapbox loads, I found that a significant majority of our users are accessing the site on mobile devices (over 65% for FRAM). On mobile devices, the map isn't displayed until the user clicks the "Open in Fullscreen" option. However, we're currently initializing the map as soon as the page loads, even though it's not visible. This PR optimizes the process by delaying the map's initialization until it is actually opened in fullscreen, which should help reduce our costs.
Part of https://github.com/AtB-AS/kundevendt/issues/18810

refactor: initialize map on mobile devices when opened

---

src/page-modules/assistant/server/journey-planner/index.ts
src/page-modules/assistant/server/journey-planner/journey-gql/trip-with-details.gql
src/page-modules/assistant/server/journey-planner/journey-gql/via-trip-with-details.gql
src/page-modules/assistant/server/journey-planner/validators.ts

This reverts commit 94660fd36fa5a6fb73490aa5e897d78d488104b4.
Reverting this because of changes to where we should display the messages (see PR in app) and we need to do a planner-web release (https://github.com/AtB-AS/kundevendt/issues/4203)

Revert "Extend notifications to include behovsanlop. (#320)"

---

src/page-modules/departures/__tests__/departure-data.fixture.ts
src/page-modules/departures/__tests__/departure-details.test.tsx
src/page-modules/departures/__tests__/service-journey-data.fixture.ts
src/page-modules/departures/details/index.tsx
src/page-modules/departures/server/journey-planner/index.ts
src/page-modules/departures/server/journey-planner/journey-gql/departures.gql
src/page-modules/departures/server/journey-planner/journey-gql/estimated-calls.gql
src/page-modules/departures/server/journey-planner/journey-gql/service-journey-with-estimated-calls.gql
src/page-modules/departures/server/journey-planner/validators.ts
src/page-modules/departures/stop-place/index.tsx
src/page-modules/departures/utils.ts
src/translations/dictionary.ts

We're currently not using the via information found in the destination display object and are therefore giving different information than in the app. This updates the line names for the departure and departure details pages. 
<details>
</details>

feat: show destination display via information

---

src/page-modules/contact/layouts/contact-page-layout.tsx
src/page-modules/contact/layouts/layout.module.css

I've added icons to the contact page navigator. Also updated the "active-border" to use the design-system.

feat: icons for the contact page navigator

---

src/page-modules/contact/error-content/error-content.module.css
src/page-modules/contact/error-content/error-content.tsx
src/page-modules/contact/success-content/success-content.module.css
src/page-modules/contact/success-content/success-content.tsx
src/pages/contact/error.tsx
src/pages/contact/success.tsx
src/translations/pages/contact.ts

Added a generic error and success page that users can be redirected to on error/success when submitting a form.

feat: error and success pages for contact page

---

src/layouts/shared/page-header.module.css
src/layouts/shared/page-header.tsx
src/page-modules/contact/layouts/contact-page-layout.tsx
src/page-modules/contact/layouts/layout.module.css
src/translations/pages/contact.ts

I've refactored the header to not use bold typo, have the contact page link to the right and added a "back to travel search" button for the contact layout.

fix: page header styling and contact layout

---

src/layouts/shared/page-header.tsx

Comment out link to contact page. Navigating to the contact page stil works when typing `/contact` directly into the search bar.

chore: comment out link to contact page

---

src/page-modules/contact/means-of-transport/index.tsx
src/page-modules/contact/means-of-transport/means-of-transport-form-machine.ts
src/page-modules/contact/ticket-control/index.tsx
src/page-modules/contact/ticket-control/ticket-control-form-machine.ts
src/page-modules/contact/travel-guarantee/index.tsx
src/page-modules/contact/travel-guarantee/travelGuaranteeFormMachine.ts

When a form is successfully submitted, we navigate the user to /contact/success; if it fails, we navigate to /contact/error. While submitting we disable the submit button and add a loading indicator.

feat: success and error handling

---

src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
src/page-modules/contact/ticket-control/index.tsx
src/page-modules/contact/ticket-control/ticket-control-form-machine.ts

This PR includes:
- The logic inside `ON_INPUT_CHANGE` is update so that `agreesSecondAgreement` is automatically set to `false` whenever `agreesFirstAgreement` is set to `false`.
- A new condition is added to control the visibility of the submit button.

fix: button display

---

src/page-modules/contact/components/input/file.tsx

This prevents the browser from opening the file when dropped above the file-input.

feat: drag and drop files

---

src/page-modules/contact/components/input/file.tsx

It's currently only possible to upload files taken with the camera on mobile devices. Removing `capture` lets the user decide whether to take an image or upload an existing one.

fix: file attachment capture attribute

---

src/page-modules/contact/means-of-transport/forms/delayForm.tsx
src/page-modules/contact/means-of-transport/forms/driverForm.tsx
src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
src/page-modules/contact/means-of-transport/forms/stopForm.tsx
src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
src/page-modules/contact/ticket-control/forms/postponePayment.tsx
src/page-modules/contact/travel-guarantee/form-selector.tsx
src/page-modules/contact/travel-guarantee/index.tsx
src/page-modules/contact/validation/commonInputValidator.ts
src/page-modules/contact/validation/special-field-validators/travelGuaranteeInputValidator.ts
src/page-modules/contact/validation/utils.ts
src/translations/pages/contact.ts

- Translation improvements.
- Renaming of translation objects. 
- Some reorganisation of translation objects.

chore: cleanup translations 

---

src/page-modules/contact/commoneEvents.ts
src/page-modules/contact/means-of-transport/forms/delayForm.tsx
src/page-modules/contact/means-of-transport/forms/driverForm.tsx
src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
src/page-modules/contact/means-of-transport/forms/stopForm.tsx
src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
src/page-modules/contact/means-of-transport/means-of-transport-form-machine.ts
src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
src/page-modules/contact/ticket-control/ticket-control-form-machine.ts
src/page-modules/contact/travel-guarantee/index.tsx
src/page-modules/contact/travel-guarantee/travelGuaranteeFormMachine.ts
src/page-modules/contact/utils.ts

This PR adds `setTransportModeAndResetLineAndStops` `setLineAndResetStops`, two functions used to  correctly handle `line`, `fromStop` and `toStop` whenever `transportMode` and/or `line` is set.

fix: handling reseting transport mode and line. 

---

src/page-modules/contact/components/input/input.module.css

When in Safari, after submitting, the width of input fields is adjusted when using tab to navigate between them.    
Submit button. Then, navigate between the input fields using tab. 
<details>
<Summary>Before fix</Summary>
https://github.com/user-attachments/assets/5035cba5-c8c8-437e-a9c5-772073a4eb54
</details>
<details>
<Summary>After fix</Summary>
https://github.com/user-attachments/assets/ef4c79e8-5492-4510-b3f2-35181c75f359
</details>

fix: consistent width of input fields in Chrome, FireFox and Safari.  

---

src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
src/page-modules/contact/ticket-control/ticket-control-form-machine.ts
src/page-modules/contact/travel-guarantee/forms/refundCarForm.tsx
src/page-modules/contact/travel-guarantee/forms/refundTaxiForm.tsx
src/page-modules/contact/travel-guarantee/travelGuaranteeFormMachine.ts
src/page-modules/contact/validation/commonInputValidator.ts
src/translations/pages/contact.ts

chore: add conditional validation of bankAccountNumber, IBAN and SWIFT 

---

src/page-modules/contact/layouts/contact-page-layout.tsx
src/page-modules/contact/lost-property/index.tsx
src/pages/contact/lost-property.tsx
src/translations/pages/contact.ts

Added the lost property contact page:

feat: lost property contact page

---

src/page-modules/contact/travel-guarantee/travelGuaranteeFormMachine.ts

Add condition to hide button and forms isInitialAgreementChecked is toggled from true to false.
https://github.com/user-attachments/assets/2ed6c998-6d69-4899-881d-13299db05774
https://github.com/user-attachments/assets/aeeda69d-e341-432a-8f18-42e3bcaa4ef6

fix: hide travel guarantee forms when agreement is unchecked

---

src/page-modules/contact/group-travel/group-travel-state-machine.ts
src/page-modules/contact/group-travel/group-travel.module.css
src/page-modules/contact/group-travel/index.tsx
src/page-modules/contact/server/contact/index.ts
src/pages/api/contact/group-travel.ts
src/pages/contact/group-travel.tsx
src/translations/pages/contact.ts

Added a new form for the group travel contact page. 
A few things worth looking into:
- Simplified input change handling by updating the entire form
- Splitting context into multiple objects (such as `formData` and `errors`) 
- Local error handling to not be dependent on other forms
- Use `assign` for actions to get updated context data (ref. `const [forceRerender, setForceRerender] = useState(false);` in other state machines) 
<details>
</details>

feat: group travel contact page

---

src/page-modules/contact/components/input/input.module.css

This PR changes the border width of the input elements to use the `--border-width-slim`:

fix: border width of input elements

---

src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
src/page-modules/contact/validation/commonInputValidator.ts
src/translations/pages/contact.ts

Move `appPhoneNumber`, `customerNumber` and `travelCardNumber` into `input` in `contacts.ts`, as these inputs are used in other contexts in addition to ticketControl.feeComplaint.

refactor:  minor update in the organization of translation objects

---

src/page-modules/contact/group-travel/index.tsx
src/page-modules/contact/means-of-transport/forms/delayForm.tsx
src/page-modules/contact/means-of-transport/forms/driverForm.tsx
src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
src/page-modules/contact/means-of-transport/forms/stopForm.tsx
src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
src/page-modules/contact/server/journey-planner/index.ts
src/page-modules/contact/server/journey-planner/journey-gql/lines.gql
src/page-modules/contact/server/journey-planner/validators.ts
src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
src/page-modules/contact/travel-guarantee/forms/refundCarForm.tsx
src/page-modules/contact/travel-guarantee/forms/refundTaxiForm.tsx
src/page-modules/contact/utils.ts

Added public code to the line selector in the contact form:

feat: display public code for lines in contact form

---

src/page-modules/contact/travel-guarantee/forms/refundCarForm.tsx
src/translations/pages/contact.ts

Closes https://github.com/AtB-AS/kundevendt/issues/19328
Feedback from FRAM:
Her blir jeg veldig forvirret. Burde det ikke spørres om bilreisen først, slik Ruter gjør? Hos oss kommer spørsmål om antall kjørte kilometer og til/fra under tittelen
Om den planlagte reisa di.
Spilt up the section `Om den planlagte reisa di` into two sections:
Kilometer køyrd
Frå adresse
Til adresse
Fortel kvifor du ikkje fekk reist som du skulle med oss, slik at du måtte ta drosje.
Transportmiddel
[Moglege val]
Buss
Hurtigbåt
.....

fix: travel guarantee - split section into two sections

---

src/page-modules/contact/ticketing/events.ts
src/page-modules/contact/ticketing/forms/travel-card/index.tsx
src/page-modules/contact/ticketing/forms/travel-card/orderTravelCardForm.tsx
src/page-modules/contact/ticketing/forms/travel-card/travelCardQuestionForm.tsx
src/page-modules/contact/ticketing/index.tsx
src/page-modules/contact/ticketing/ticketingStateMachine.ts
src/translations/pages/contact.ts

This PR provides a forms for travel card, under the ticketing page.
Blocked until `handlerTravelCardForm` is added to `ticketingRouter`: https://github.com/mrfylke/pureservice-connect/pull/16

feat: add ticketing travelcard forms

---

src/page-modules/contact/commoneEvents.ts
src/page-modules/contact/lines/use-lines.ts
src/page-modules/contact/means-of-transport/forms/delayForm.tsx
src/page-modules/contact/means-of-transport/forms/driverForm.tsx
src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
src/page-modules/contact/means-of-transport/forms/stopForm.tsx
src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
src/page-modules/contact/means-of-transport/means-of-transport-form-machine.ts
src/page-modules/contact/server/journey-planner/index.ts
src/page-modules/contact/server/journey-planner/journey-gql/lines.gql
src/page-modules/contact/server/journey-planner/validators.ts
src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
src/page-modules/contact/ticket-control/ticket-control-form-machine.ts
src/page-modules/contact/travel-guarantee/forms/refundCarForm.tsx
src/page-modules/contact/travel-guarantee/forms/refundTaxiForm.tsx
src/page-modules/contact/travel-guarantee/travelGuaranteeFormMachine.ts
src/page-modules/contact/types.ts
src/page-modules/contact/utils.ts
src/translations/pages/contact.ts

Closes https://github.com/AtB-AS/kundevendt/issues/19324
I FRAM har vi buss, hurtigbåt og ferje. Avviksinformasjonen vår er også delt inn på dette. Burde det ikke være mulig å velge «ferje» eller «hurtigbåt» under transportmiddel, i stedet for bare «båt»?
Update getLinesByMode() to be able to filter on bus, express boats and ferry
<details>
</details>

feat: extend line filtering to filter by bus, fast ferry and ferry.

---

src/page-modules/contact/lines/use-lines.ts

This PR specifies the correct sub transport modes for express boat.

fix: specify the correct sub transport modes for express boat

---

src/page-modules/contact/travel-guarantee/index.tsx
src/translations/pages/contact.ts

Closes https://github.com/AtB-AS/kundevendt/issues/19326
This PR specifies that travel guarantee does not apply for ferries, and adds a link to the travel guarantee info page on frammr.no.

feat: add link to travel guarantee page

---

src/page-modules/contact/travel-guarantee/events.ts
src/page-modules/contact/travel-guarantee/forms/refundTaxiForm.tsx
src/page-modules/contact/travel-guarantee/travelGuaranteeFormMachine.ts
src/page-modules/contact/validation/commonInputValidator.ts
src/translations/pages/contact.ts

Closes https://github.com/AtB-AS/kundevendt/issues/19327
This PR adds the missing section in the travel guarantee taxi refund form. A component for enable use of mobile camera to directly upload images is not included. This should be a separate PR.

fix: add missing section in travel guarantee taxi refund form

---

src/page-modules/contact/components/form/select.tsx
src/page-modules/contact/layouts/contact-page-layout.tsx
src/page-modules/contact/layouts/layout.module.css
src/translations/pages/contact.ts

This PR extends the contact page layout to be displayed as a dropdown in mobile view. 
<details>
https://github.com/user-attachments/assets/4737592f-f5d1-44d0-8f28-62484ab0b07f
</details>

feat: display contact page layout as dropdown in mobile view 

---

src/page-modules/contact/components/form/form.module.css
src/page-modules/contact/components/form/searchable-select/searchable-select.tsx
src/page-modules/contact/components/form/select.tsx

Currently, the `Select` and `SearchableSelect` components have different appearances. It is desirable that these components have the same appearance.  
<details>
</details>
- The appearance of the `Select` component is updated to appear more similar to the `SearchableSelect` component. 
- The font-size of both `Select` and `SearchableSelect` is increased in mobile view. 
- Removes some unused css classes.

fix: update the appearance of the select component

---

src/page-modules/contact/components/form/form.module.css
src/page-modules/contact/components/form/searchable-select/searchable-select.tsx
src/page-modules/contact/components/form/select.tsx

Minor changes to the css styling of `Select` and `SearchableSelect`. The PR includes the following changes:
- Checkmark is moved to the right side of the selector option text.
- Bg-color for highlighted option is changes to  `var(--interactive-interactive_2-active-background)`, same as used in `webshop2`.
- Added :active to highlight active options for user in both `Select` and `SearchableSelect`.  
I also considered doing more changes to make the selectors more similar the combobox in `webshop2`, but decided not to because the combobox in my opinion takes  up a bit too much space in the mobile view. Feel free to give feedback on this.

chore: minor styling update for searchable selector and select

---

src/page-modules/contact/components/form/date-selector.tsx
src/page-modules/contact/components/form/form.module.css
src/page-modules/contact/components/form/index.ts
src/page-modules/contact/components/index.tsx
src/page-modules/contact/means-of-transport/forms/delayForm.tsx
src/page-modules/contact/means-of-transport/forms/driverForm.tsx
src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
src/page-modules/contact/means-of-transport/forms/stopForm.tsx
src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
src/page-modules/contact/travel-guarantee/forms/refundCarForm.tsx
src/page-modules/contact/travel-guarantee/forms/refundTaxiForm.tsx

Currently, the date format displayed on the contact page depends on the date format the users browsers is set to. It is desirable to always displayed the date as dd.mm.yyyy - format. 
In FireFox:
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
Use  a custom date picker component to always display the correct date format.

feat: custom date selector component 

---

src/page-modules/contact/components/form/form.module.css
src/page-modules/contact/components/form/index.ts
src/page-modules/contact/components/form/time-selector.tsx
src/page-modules/contact/components/index.tsx
src/page-modules/contact/means-of-transport/forms/delayForm.tsx
src/page-modules/contact/means-of-transport/forms/driverForm.tsx
src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
src/page-modules/contact/travel-guarantee/forms/refundCarForm.tsx
src/page-modules/contact/travel-guarantee/forms/refundTaxiForm.tsx

Currently, the time format displayed on the contact page depends on the time format the users browsers is set to. This means that both the 12 hours (AM/PM time format) and 24 hours (military time format) can be displayed. It is desirable to always displayed the time in 24 hour format.  
Corresponding styling of component is already defined in this PR: https://github.com/AtB-AS/planner-web/pull/417
In FireFox:
<details>
<summary>Before</summary>
| Before    | After |
| -------- | ------- |
|<img width="368" alt="Skjermbilde 2024-11-07 kl  09 40 05" src="https://github.com/user-attachments/assets/a472b9d2-c57e-4dd0-b6b3-267209f71148"> | <img width="368" alt="Skjermbilde 2024-11-07 kl  09 39 34" src="https://github.com/user-attachments/assets/6e25f20a-d682-4864-b2c1-95f9952b4e62"> |
| <img …

feat: custom time selector component 

---

src/page-modules/contact/contact.module.css

Closes https://github.com/AtB-AS/kundevendt/issues/19502
Currently, the button is always as wide as the parent component. When displayed on wide screens, the button becomes very wide. 
<details>
</details>
Add a max width to the submit button. The max width is removed in mobile view.

chore: add max width to submit button

---

src/page-modules/contact/components/form/input.tsx
src/page-modules/contact/group-travel/index.tsx
src/page-modules/contact/means-of-transport/forms/delayForm.tsx
src/page-modules/contact/means-of-transport/forms/driverForm.tsx
src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
src/page-modules/contact/means-of-transport/forms/stopForm.tsx
src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
src/page-modules/contact/ticket-control/forms/postponePayment.tsx
src/page-modules/contact/ticketing/forms/app/appAccountForm.tsx
src/page-modules/contact/ticketing/forms/app/appTicketingForm.tsx
src/page-modules/contact/ticketing/forms/app/appTravelSuggestionForm.tsx
src/page-modules/contact/ticketing/forms/priceAndTicketTypesForm.tsx
src/page-modules/contact/ticketing/forms/refund/appTicketRefund.tsx
src/page-modules/contact/ticketing/forms/refund/otherTicketRefund.tsx
src/page-modules/contact/ticketing/forms/travel-card/orderTravelCardForm.tsx
src/page-modules/contact/ticketing/forms/travel-card/travelCardQuestionForm.tsx
src/page-modules/contact/ticketing/forms/webshop/webshopAccountForm.tsx
src/page-modules/contact/ticketing/forms/webshop/webshopTicketingForm.tsx
src/page-modules/contact/travel-guarantee/forms/refundCarForm.tsx
src/page-modules/contact/travel-guarantee/forms/refundTaxiForm.tsx

Update input label property type from `TranslationString` to `string`.

chore: update input label property type

---

src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
src/page-modules/contact/ticketing/forms/refund/otherTicketRefund.tsx
src/page-modules/contact/travel-guarantee/forms/refundCarForm.tsx
src/page-modules/contact/travel-guarantee/forms/refundTaxiForm.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/19509
Tilbakemelding fra FRAM:
Jeg syns det er litt forvirrende at det står «Jeg har et utenlandsk bankkontonummer» før feltet for bankkonto. Jeg tror jeg hadde kommet til å hoppe over å fylle ut bankkontonummer fordi jeg tenkte at dette kun gjaldt for de som har utenlandsk bankkontonummer. Ønsker avkryssingen for utenlandsk kontonummer under feltet for å fylle ut bankkonto, da jeg tror det er mer logisk.
<details>
</details>

feat: reorganize display of bank account input fields

---

src/page-modules/contact/components/form/form.module.css
src/page-modules/contact/components/form/select.tsx

Extend selector label to better illustrate when the selector is disabled.

feat: extend selector label to better illustrate when the selector is disabled

---

src/page-modules/contact/components/form/description-modal.tsx
src/page-modules/contact/components/form/form.module.css
src/page-modules/contact/components/form/index.ts
src/page-modules/contact/components/form/input.tsx
src/page-modules/contact/components/index.tsx
src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
src/page-modules/contact/ticket-control/forms/postponePayment.tsx
src/page-modules/contact/ticketing/forms/app/appAccountForm.tsx
src/page-modules/contact/ticketing/forms/app/appTicketingForm.tsx
src/page-modules/contact/ticketing/forms/refund/appTicketRefund.tsx
src/page-modules/contact/ticketing/forms/refund/otherTicketRefund.tsx
src/page-modules/contact/ticketing/forms/webshop/webshopTicketingForm.tsx
src/translations/pages/contact.ts

Currently, the description modal display information through a  single string. This can look a bit strange, especially when the string starts to get long, and if it is desired to list a lot of information. 
This PR extends the description model with more properties to present information in a nicer way.  
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
Add bullet point list and instruction properties to description modal.

feat: extend description mode with list and instruction properties

---

src/page-modules/contact/components/form/date-selector.tsx
src/page-modules/contact/group-travel/group-travel-state-machine.ts
src/page-modules/contact/means-of-transport/forms/delayForm.tsx
src/page-modules/contact/means-of-transport/forms/driverForm.tsx
src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
src/page-modules/contact/means-of-transport/means-of-transport-form-machine.ts
src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
src/page-modules/contact/ticket-control/ticket-control-form-machine.ts
src/page-modules/contact/travel-guarantee/forms/refundCarForm.tsx
src/page-modules/contact/travel-guarantee/forms/refundTaxiForm.tsx
src/page-modules/contact/travel-guarantee/travelGuaranteeFormMachine.ts
src/page-modules/contact/utils.ts

Closes https://github.com/AtB-AS/kundevendt/issues/19523
Currently, the date is automatically set when reporting an incident. This results in several users sloppily specifying the correct date, which is again critical information. 
Date of an incident should be mandatory to provided when needed. The user must specify the date himself.
<details>
</details>

feat: set the date of the incident manually

---

src/page-modules/contact/means-of-transport/events.ts
src/page-modules/contact/means-of-transport/forms/driverForm.tsx
src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
src/page-modules/contact/means-of-transport/means-of-transport-form-machine.ts
src/page-modules/contact/validation/commonInputValidator.ts
src/translations/pages/contact.ts

Remove the property `area` from all contact forms, as this property is redunat as the users already are providing information about line and stop place.

fix: remove property area from contact forms

---

src/page-modules/contact/group-travel/group-travel-state-machine.ts
src/page-modules/contact/group-travel/index.tsx

Currently, time and date on the `/group-travel` page is set through the `Input` component. This PR updates the page to start using the `DateSelector` and the `TimeSelector`.  
<details>
</details>

feat: extend the group travel page with both date and time selector

---

src/page-modules/contact/means-of-transport/forms/delayForm.tsx
src/page-modules/contact/means-of-transport/forms/driverForm.tsx
src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
src/page-modules/contact/travel-guarantee/forms/refundCarForm.tsx
src/page-modules/contact/travel-guarantee/forms/refundTaxiForm.tsx

Remove redundant fallback value `|| ''` from `TimeSelector` component.

fix: remove redundant fallback value

---

src/page-modules/contact/utils.ts

Closes https://github.com/AtB-AS/kundevendt/issues/19546
Currently, the validation message for the `bankAccountNumber` input field does not disappear when toggling from highlighting the input field displaying `bankAccountNumber` to displaying the input fields for `SWIFT` and `IBAN`. The validation message should disappear to avoid confusion the users. 
<details>
<summary>video</summary>
https://github.com/user-attachments/assets/4790ddf0-d52e-4f33-a7fc-a0b87ec981ac
</details>

fix: remove validation message when toggling between the input fields

---

src/page-modules/contact/components/form/time-selector.tsx

A runtime error appears when updating the time using the `TimeSelector`. 
- First, enter a time. For example: `11:00`.
- Second, attempt updating the time på for `:00` by tapping the the delete button. 
<details>
<Summary>screenshots</Summary>
</details>

fix: add condition to avoid runtime error

---

src/page-modules/contact/ticket-control/events.ts
src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
src/page-modules/contact/ticket-control/ticket-control-form-machine.ts
src/page-modules/contact/validation/commonInputValidator.ts
src/translations/pages/contact.ts

Closes https://github.com/AtB-AS/kundevendt/issues/19548
Currently, the same labels are used for all date and time input fields in the contact form. Both labels can be formulated to be more specific, making it easier for the user to understand which date and which time should be given.
This PR updates the translations, and specifies the property names to be more descriptive. 
<details>
</details>
- Add the two new objects `date` and `time`  in `contact.ts`. These objects will contain translations which better describes the context of the forms they are being used in.   
- Specify property names in state machine to be more descriptive.

fix: update translations of date and time properties in ticket control state machine

---

src/translations/pages/contact.ts

Update from 'Jeg forsår', to 'Jeg forstår'.

fix: translation typo

---

src/page-modules/contact/ticketing/ticketingStateMachine.ts

Remove attachments from inputs to validate, as attachments should optional to include.

fix: update attachments to be optional in app forms

---

src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/index.tsx

Currently, the situation icon is displayed when, even though the situation message it self is not displayed.  
<details>
<Summary>screenshots/video</Summary>
</details>
Use the function `isSituationValidAtDate(new Date())` to ensure that icon is only displayed for situation within the validity period.

fix: ensure that situation icons are only displayed during the validity period

---

src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
src/page-modules/contact/ticket-control/ticket-control-form-machine.ts
src/translations/pages/contact.ts

Closes https://github.com/AtB-AS/kundevendt/issues/19559
Feedback from fram:
Ønsker ikke å kreve holdeplasser for billettkontroll skjema. Altså:
- Må ha linje
- Må ha tidspunkt
- Ikke holdeplasser
<details>
</details>
Make `fromStop` and `toStop` input fields optional.

fix: make fromStop and toStop input fields optional in ticket control feedback form

---

src/page-modules/assistant/details/trip-section/index.tsx
src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/index.tsx

Situations are not shown correctly on the assistant page. These changes should only be applied to the departure pages.

fix: situations for assistant page 

---

src/page-modules/contact/contact.module.css

This PR removes the padding from the css class `.rules_list`. This is tiny change, but in my opinion looks better.   
| Before  |  After  |   
|---|---|
| <img width="789" alt="Skjermbilde 2024-11-27 kl  12 03 59" src="https://github.com/user-attachments/assets/62de4216-619b-4b87-a4fd-c0f1f3d2f894"> | <img width="774" alt="Skjermbilde 2024-11-27 kl  12 04 12" src="https://github.com/user-attachments/assets/23ef72e2-24ad-4089-99ae-61d205375b5c"> | 
| <img width="822" alt="Skjermbilde 2024-11-27 kl  12 04 47" src="https://github.com/user-attachments/assets/55b62c49-7bfe-4322-a8dd-3f3c38943c9e"> | <img width="822" alt="Skjermbilde 2024-11-27 kl  12 04 36" src="https://github.com/user-attachments/assets/ce8a5c6e-3742-4cd8-9862-a552c098fa5d"> |

style: remove excessive padding around list

---

src/page-modules/contact/travel-guarantee/index.tsx
src/translations/pages/contact.ts

Closes https://github.com/AtB-AS/kundevendt/issues/19617
Etter overskriften «I hvilke tilfeller gjelder ikke reisegarantien», skal det settes inn denne setningen:
«Reisegarantien gjeld ikkje for ferjene. Reisegarantien gjeld heller ikke for flybussen i Ålesund eller andre kommersielle busslinjer.»
<details>
</details>

fix: add a new exception to travelguarantee

---

src/layouts/shared/footer.tsx

Avoid opening a new TAB when clicking on the link in the footer to the new contact form.

fix: avoid opening new tab when clicking on link to contact form

---

src/page-modules/contact/ticketing/forms/refund/otherTicketRefund.tsx
src/page-modules/contact/travel-guarantee/forms/refundCarForm.tsx
src/page-modules/contact/travel-guarantee/forms/refundTaxiForm.tsx
src/translations/pages/contact.ts

Close https://github.com/AtB-AS/kundevendt/issues/19625#issue-2704445305
Currently in the contact form, `App` or `Travelcard` are the only available options for when asking the user to specify where his ticket is stored.  `App` is too vague and can lead tho misunderstandings. A better solution would be to display the name of the app, or a list of names if the ticket can be stored on several apps. 
<details>
</details>
Change  the radio button text from `App` to the app name(s)  where the ticket can be found.

chore: make radio button text more descriptive 

---

src/page-modules/contact/components/form/select.tsx

Add toLowerCase() to avoid undefined values in case of upper case letters being used in the ids.

fix: ensure case-insensitive matching of selected IDs in custom selector

---

src/page-modules/contact/refund/forms/refund-ticket/appTicketRefund.tsx
src/page-modules/contact/refund/refundFormMachine.ts

Close https://github.com/AtB-AS/kundevendt/issues/19703
Utvid skjema med et tesktfelt for å beskrive hvorfor man ønsker refusjon for billettkjøpet. 
<details>
</details>

feat: add refund reason to appTicketRefund form

---

.env.example
orgs/farte.json
orgs/schema-validation.json
src/layouts/shared/footer.tsx
src/modules/org-data/index.tsx
src/modules/theme/index.ts
src/translations/modules/layout.ts

Adds an optional `forceTheme` option to `OrgData`, which disables dark theme toggling and forces the specified theme.
This is useful for organizations without a dark theme (or light theme), like Farte.
Without `"forceTheme"` in `farte.json`:
With `"forceTheme": "light"` in `farte.json`:

feat: force Farte light theme

---

src/pages/api/contact/contact-api-config.ts
src/pages/api/contact/means-of-transport.ts
src/pages/api/contact/refund.ts
src/pages/api/contact/ticket-control.ts
src/pages/api/contact/ticketing.ts

Close https://github.com/AtB-AS/kundevendt/issues/19769
When posting a form 1MB or larger, the status code 413 appears. This is due to NEXT default body size limit which is set to 1MB. When posting forms with attachments, the size of the body can easily exceed 1MB. When this happens, the screen start to buffer.

fix: specify post body size limit for contact form api  

---

src/page-modules/assistant/details/index.tsx
src/page-modules/assistant/details/trip-section/index.tsx
src/page-modules/assistant/details/trip-section/interchange-section.tsx
src/page-modules/assistant/details/utils.ts
src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/__tests__/trip-pattern-header.test.tsx
src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/index.tsx
src/page-modules/assistant/trip/trip-pattern/utils.ts
src/page-modules/departures/details/estimated-call-rows.tsx
src/page-modules/departures/details/utils.ts
src/page-modules/departures/stop-place/index.tsx
src/translations/dictionary.ts
src/translations/pages/assistant.ts
src/translations/pages/departures.ts

VKT requested a prefix for quay public codes, similar to entur.no
> entur.no
>
> <img width="214" alt="image" src="https://github.com/user-attachments/assets/0f62f1b1-13fb-4b81-be58-426cb57eecc1" />

feat: quay public code prefix

---

src/page-modules/contact/refund/forms/residualValueOnTravelCard/index.tsx
src/page-modules/contact/refund/index.tsx
src/page-modules/contact/refund/refundFormMachine.ts
src/translations/pages/contact.ts

Closes https://github.com/AtB-AS/kundevendt/issues/19822
The contact form should link to an already existing form used to apply for refund of residual value on a travel card.
<details>
</details>

feat: add page with link to form for retrieving residual value on travel cards

---

src/translations/pages/assistant.ts
src/translations/server/endpoints.ts

Defined org-specific translations for VKT and Farte to be used instead of AtB defaults.

feat: update org-specific ticket message and line number hint

---

src/pages/api/contact/contact-api-config.ts
src/pages/api/contact/means-of-transport.ts
src/pages/api/contact/refund.ts
src/pages/api/contact/ticket-control.ts
src/pages/api/contact/ticketing.ts

Define body size limit in all contact form endpoints, as NEXT does not support import of config.

fix: update config for contact api endpoints 

---

src/components/message-box/index.tsx
src/components/message-box/message-box.module.css
src/modules/global-messages/context.tsx
src/modules/global-messages/global-messages.tsx
src/modules/global-messages/types.ts
src/page-modules/assistant/details/details.module.css
src/page-modules/assistant/details/index.tsx
src/page-modules/assistant/trip/index.tsx
src/page-modules/departures/__tests__/departure-details.test.tsx
src/page-modules/departures/__tests__/departure.test.tsx
src/page-modules/departures/details/index.tsx
src/page-modules/departures/stop-place/index.tsx
src/page-modules/departures/stop-place/stop-place.module.css

feat: more global messages contexts

---

src/components/message-box/index.tsx
src/components/message-box/message-box.module.css
src/modules/global-messages/context.tsx
src/modules/global-messages/global-messages.tsx
src/utils/use-interval.ts
src/utils/use-localstorage.ts
src/utils/use-now.ts

Global messages will now respect the `isDismissable`, `startDate` and `endDate` if present.
Implementation is heavily inspired by webshop2

feat: time-specific and dismissable global messages

---

next-sitemap.js

Updated `robots.txt` generator to use `Disallow` for non-`production` environments, i.e. `staging` and `dev`.
Mainly to avoid this situation:

fix: disallow robots in non-production

---

src/modules/global-messages/types.ts

Don't know if the old implementation is on purpose, but it seems a little odd so here is a suggestion. 
The old implementation would not accept a globalMessage unless **all** of the values in `context` existed in `GlobalMessageContextEnum`. Examples of where this is not true are `app-assistant` and `app-ticketing`. 
Added a little flexibility where values in `GlobalMessageContextEnum` are checked and cast as such, but other values are discarded. Also added some documentation on this.

fix: Fixed too strict zod-schema for global messages

---

src/components/search/__tests__/search.test.tsx
src/components/search/index.ts
src/components/search/search.module.css
src/components/search/search.tsx
src/components/search/use-geolocation.tsx
src/page-modules/assistant/layout.tsx
src/page-modules/departures/layout.tsx
src/translations/components/search.ts

https://github.com/user-attachments/assets/46782c40-e6e5-4196-ad0d-39acfa6bd657
closes https://github.com/AtB-AS/kundevendt/issues/20062

feat: add location search history

---

src/components/search/search.module.css

Adds a tiny border around the search dropdown, which was missing in https://github.com/AtB-AS/kundevendt/issues/20062

feat: add border around search dropdown

---

src/components/map/map-header.tsx
src/page-modules/assistant/__tests__/assistant.test.tsx
src/page-modules/assistant/details/utils.ts
src/page-modules/assistant/trip-query-fetcher.ts
src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/__tests__/trip-pattern-header.test.tsx
src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/__tests__/trip-pattern.fixture.ts
src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/index.tsx
src/page-modules/assistant/trip/trip-pattern/utils.ts
src/page-modules/assistant/types.ts
src/page-modules/assistant/utils.ts
src/page-modules/departures/fetch-departure-query.ts
src/page-modules/departures/utils.ts

closes https://github.com/AtB-AS/kundevendt/issues/20033
Switched the reverse geocoder into autocomplete to allow same behavior with the app. Trip search and departure now should no longer converts "Prinsens Gate 39" into "Quality Hotel Augustin".
https://github.com/user-attachments/assets/9ef26594-88ba-4e76-8f5f-f3a16fa052f1

feat: use autocomplete data instead of reverse geocoder for trip search and departure

---

src/page-modules/contact/refund/events.ts
src/page-modules/contact/refund/forms/refund-ticket/appTicketRefund.tsx
src/page-modules/contact/refund/refundFormMachine.ts
src/page-modules/contact/types.ts
src/page-modules/contact/validation/commonInputValidator.ts
src/translations/pages/contact.ts

feat: extend contact form with selector to specify which platform the ticket was purchases through

---

src/translations/pages/contact.ts

Remove bullet point about rule that no longer applies from contact form

chore:  remove bullet point about rule that no longer applies

---

src/page-modules/contact/layouts/contact-page-layout.tsx
src/page-modules/contact/layouts/layout.module.css
src/translations/pages/contact.ts

Include message telling users not to provide personal information unless asked after in the contact form. Visible to all forms.

feat: add message to inform users to not include personal information

---

src/page-modules/contact/components/form/form.module.css
src/page-modules/contact/components/form/input.tsx
src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundCarForm.tsx
src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundTaxiForm.tsx
src/page-modules/contact/refund/forms/refund-ticket/otherTicketRefund.tsx
src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
src/page-modules/contact/validation/validationRules.ts
src/translations/pages/contact.ts

Extend validation bank account number in contact form

feat: extend validation bank account number in contact form

---

README.md
src/modules/cookies/cookies-context.tsx
src/pages/widget/fullscreen/[[...version]].tsx

This makes it possible to access a version of the widget a bit more "in context".
Made as part of becoming familiar with the widget ~~not sure if we should merge this?~~ To be merged due to [_popular demand_](https://github.com/AtB-AS/planner-web/pull/531#issuecomment-2835374418).
Going to `http://localhost:3000/widget/fullscreen` will default to the most recent version of the widget, or a specific version can be selected, such as e.g. `http://localhost:3000/widget/fullscreen/2.0.0`
The implementation is mostly based on the existing `src/pages/widget/index.tsx`.

Widget in its more natural habitat

---

src/page-modules/assistant/server/journey-planner/index.ts

Unexpected behavior has been reported concerning the via search. Since the max slack has been set to 9 hours, a high number of suggestions will be returned for the same second departure (see image). The reason behind the 9 hours seems to be lost (and no significant use-case identified by AtB or FRAM), so reducing to 2 hours for now.

feat: reduce maxSlack in viaTripQuery

---

src/page-modules/contact/components/form/date-selector.tsx
src/page-modules/contact/components/form/form.module.css
src/page-modules/contact/components/form/time-selector.tsx

Move Label inside DatePicker and TimeFiled to avoid aria-lable error messages. Afterwards, update the css styling to make the components appear as before.
| Before | After |
|--------|--------|
| <img width="1070" alt="Skjermbilde 2025-04-29 kl  11 03 55" src="https://github.com/user-attachments/assets/529963b5-28bf-4c06-b1ec-adeac5a6c604" /> |<img width="1077" alt="Skjermbilde 2025-04-29 kl  11 04 10" src="https://github.com/user-attachments/assets/19647a96-3dc8-468c-9413-c2ba42445a3b" /> |

fix(accessibility): move label inside date/time fields to fix aria label issues in date/time components

---

src/page-modules/contact/validation/validationRules.ts

This PR fixes a bug that caused the contact form to crash during validation.
The issue occurred because several form properties `transportMode` (`TransportModeType`), `line` (`Line`), `fromStop` and `toStop` (`Line['quays'][0]`), and `attachments` (`File[]´) —are not of type `string`. However, the validation function `isNotEmptyOrUndefined` was only designed to handle `string | undefined` types, leading to runtime errors when non-string values were passed.
To resolve this:
The original isNotEmptyOrUndefined function has been split into two type-safe functions:
- isDefined() – checks if any value is not undefined
- isNonEmptyString() – checks if a value is a non-empty string (ignoring whitespace)
This ensures proper validation without type errors and improves clarity by separating …

fix: crash in form validation due to unexpected input type

---

src/page-modules/contact/components/form/textarea.tsx
src/page-modules/contact/means-of-transport/forms/delayForm.tsx
src/page-modules/contact/means-of-transport/forms/driverForm.tsx
src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
src/page-modules/contact/means-of-transport/forms/stopForm.tsx
src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundCarForm.tsx
src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundTaxiForm.tsx
src/page-modules/contact/refund/forms/refund-ticket/appTicketRefund.tsx
src/page-modules/contact/refund/forms/refund-ticket/otherTicketRefund.tsx
src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
src/page-modules/contact/ticket-control/ticket-control-form-machine.ts
src/page-modules/contact/ticketing/forms/app/appAccountForm.tsx
src/page-modules/contact/ticketing/forms/app/appTicketingForm.tsx
src/page-modules/contact/ticketing/forms/app/appTravelSuggestionForm.tsx
src/page-modules/contact/ticketing/forms/priceAndTicketTypesForm.tsx
src/page-modules/contact/ticketing/forms/travel-card/travelCardQuestionForm.tsx
src/page-modules/contact/ticketing/forms/webshop/webshopAccountForm.tsx
src/page-modules/contact/ticketing/forms/webshop/webshopTicketingForm.tsx

Add id property to textarea component. This is done to include the textarea component in the automatic focus and scroll on submit,  as described in https://github.com/AtB-AS/planner-web/pull/539.

feat: id property to textarea component

---

src/page-modules/contact/components/form/select.tsx
src/page-modules/contact/layouts/contact-page-layout.tsx
src/page-modules/contact/means-of-transport/forms/delayForm.tsx
src/page-modules/contact/means-of-transport/forms/driverForm.tsx
src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
src/page-modules/contact/means-of-transport/forms/stopForm.tsx
src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundCarForm.tsx
src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundTaxiForm.tsx
src/page-modules/contact/refund/forms/refund-ticket/appTicketRefund.tsx
src/page-modules/contact/refund/forms/refund-ticket/otherTicketRefund.tsx
src/page-modules/contact/ticket-control/forms/feedbackForm.tsx

Add id property to select component. This is done to include the select component in the automatic focus and scroll on submit, as described in https://github.com/AtB-AS/planner-web/pull/539.

feat: add id property to select component

---

src/page-modules/contact/components/form/fieldset/fieldset.module.css
src/page-modules/contact/components/form/form.module.css
src/page-modules/contact/components/form/textarea.tsx
src/page-modules/contact/means-of-transport/forms/delayForm.tsx
src/page-modules/contact/means-of-transport/forms/driverForm.tsx
src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
src/page-modules/contact/means-of-transport/forms/stopForm.tsx
src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundCarForm.tsx
src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundTaxiForm.tsx
src/page-modules/contact/refund/forms/refund-ticket/appTicketRefund.tsx
src/page-modules/contact/refund/forms/refund-ticket/otherTicketRefund.tsx
src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
src/page-modules/contact/ticketing/forms/app/appAccountForm.tsx
src/page-modules/contact/ticketing/forms/app/appTicketingForm.tsx
src/page-modules/contact/ticketing/forms/app/appTravelSuggestionForm.tsx
src/page-modules/contact/ticketing/forms/priceAndTicketTypesForm.tsx
src/page-modules/contact/ticketing/forms/travel-card/travelCardQuestionForm.tsx
src/page-modules/contact/ticketing/forms/webshop/webshopAccountForm.tsx
src/page-modules/contact/ticketing/forms/webshop/webshopTicketingForm.tsx

This PR does the following:
- Update the distances between the components used inside the contact forms, to make the forms appear less cramped. 
- Extend textarea by moving the FileInput component into textarea. 
- Extend the textarea component with the optional property `description` that can be used to describe the context of the textarea component.
| Before | After |
|--------|--------|
| <img width="933" alt="Skjermbilde 2025-05-07 kl  08 54 09" src="https://github.com/user-attachments/assets/23a10cfd-d4dc-4def-af4f-ca03de76ae66" /> | <img width="873" alt="Skjermbilde 2025-05-07 kl  08 54 54" src="https://github.com/user-attachments/assets/3ff7e90d-7dd4-473c-894c-74558b40a0c4" /> |
| Before | After |
|--------|--------|
| <img width="933" alt="Skjermbilde 2025-05-07 kl  08 53 25" …

feat: extend textarea component in contact from 

---

src/page-modules/contact/refund/events.ts
src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundCarForm.tsx
src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundTaxiForm.tsx
src/page-modules/contact/refund/forms/refund-ticket/otherTicketRefund.tsx
src/page-modules/contact/refund/refundFormMachine.ts
src/page-modules/contact/ticketing/ticketingStateMachine.ts
src/page-modules/contact/types.ts
src/page-modules/contact/validation/validationRules.ts
src/translations/pages/contact.ts

Update the validation rules to expect correct input values. Previously, the `rulesTicketType`  and `rulesReasonForTransportFailure` expected string params, and not `TicketType` and `ReasonForTransportFailure` objects, causing the rules to always return false during validation.

fix: validation error caused by wrong input types in contact form  

---

src/page-modules/contact/means-of-transport/forms/stopForm.tsx
src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundCarForm.tsx
src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundTaxiForm.tsx
src/page-modules/contact/refund/forms/refund-ticket/otherTicketRefund.tsx
src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
src/page-modules/contact/ticketing/forms/app/appTicketingForm.tsx
src/page-modules/contact/ticketing/forms/travel-card/travelCardQuestionForm.tsx
src/page-modules/contact/ticketing/forms/webshop/webshopTicketingForm.tsx
src/page-modules/contact/ticketing/ticketingStateMachine.ts
src/page-modules/contact/validation/validationRules.ts
src/translations/pages/contact.ts

This PR consists of various improvements to form validation and general language cleanup. More specifically, the following validation improvements have been made:
- Include missing errorMessage for the property `stop`.
- Extend ticketingStateMachine to validate `customerNumer` if included. 
- Extend the validation rules of of `travelCardNumber` and `postalCode`

fix: validation errors in contact form 

---

src/page-modules/assistant/assistant.module.css

(This error was hidden by the new colors in `main` since the background and input where both white)

fix: rounded top border for destination input

---

src/modules/situations/situation-or-notice-icon.tsx
src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/index.tsx
src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/rail-replacement-bus.tsx
src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/trip-pattern-header.module.css

Fixes https://github.com/AtB-AS/kundevendt/issues/20572
Moved both icons to the left side and added size modifier. 
`SituationOrNoticeIcon` is used in multiple place, therefore I added a size modifier for the icon.
`RailReplacementBus` is only used in the trips list, so I don't add size modifier and just hardcoded it as large icon.
New icons are added here https://github.com/AtB-AS/planner-web/pull/549

feat: move situation/notice icons and rail replacement bus icons

---

src/modules/situations/situation-or-notice-icon.tsx
src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/index.tsx

fix accessibility based on comment: https://github.com/AtB-AS/kundevendt/issues/20572#issuecomment-2866197649

fix: add alt text for situation and notice icons

---

src/page-modules/contact/components/form/file-input.tsx
src/page-modules/contact/means-of-transport/forms/delayForm.tsx
src/page-modules/contact/means-of-transport/forms/driverForm.tsx
src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
src/page-modules/contact/means-of-transport/forms/stopForm.tsx
src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundCarForm.tsx
src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundTaxiForm.tsx
src/page-modules/contact/refund/forms/refund-ticket/appTicketRefund.tsx
src/page-modules/contact/refund/forms/refund-ticket/otherTicketRefund.tsx
src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
src/page-modules/contact/ticketing/forms/app/appAccountForm.tsx
src/page-modules/contact/ticketing/forms/app/appTicketingForm.tsx
src/page-modules/contact/ticketing/forms/app/appTravelSuggestionForm.tsx
src/page-modules/contact/ticketing/forms/priceAndTicketTypesForm.tsx
src/page-modules/contact/ticketing/forms/travel-card/travelCardQuestionForm.tsx
src/page-modules/contact/ticketing/forms/webshop/webshopAccountForm.tsx
src/page-modules/contact/ticketing/forms/webshop/webshopTicketingForm.tsx
src/page-modules/contact/utils.ts

Enable automatic scroll to error message inside contact form, for the `FileInput` component. 
https://github.com/user-attachments/assets/4784000f-ed4c-4645-8b05-f67109fa0982

feat: enable automatic scroll to error message for file-input component

---

src/page-modules/contact/layouts/contact-page-layout.tsx
src/page-modules/contact/layouts/layout.module.css
src/translations/pages/contact.ts

Remove contact page selector from contact page layout after feedback. Should use the existing contactFormLinks in both desktop and mobile view. 
Before:
https://github.com/user-attachments/assets/3c9ed19f-fe15-4a88-9662-61604ce96933
Now:
https://github.com/user-attachments/assets/0c881a2f-fc41-468c-b758-8625571cf49b

feat: remove page selector from contact page layout

---

package.json
src/layouts/base/index.tsx
src/modules/search-time/selector/selector.module.css
src/utils/org-theme-definitions.ts
yarn.lock

Fix for AtB-AS/kundevendt#19971
Includes following changes:
- Bump of design system for new colors for Farte, since they though the yellow was too yellow. Is now black header
- Fixes that homePage-button had icon of different color than the rest of the button
- Fixes uneven padding in timeSelector ("Nå", "Avreise", "Avgang")

Small fixes for colors

---

src/translations/pages/contact.ts

Extend refundableTicketTypes translations in contact form with refund carnet ticket rule.

feat: add refund carnet ticket translation to contact form

---

src/page-modules/contact/components/form/fieldset/fieldset.module.css
src/page-modules/contact/contact.module.css
src/page-modules/contact/layouts/layout.module.css

In this PR, the spacing between and around the fieldsets used in the contact form is cleaned up to utilize more of the screen in mobile view. Also, the fieldset padding is increased.  
| Before | After |
|--------|--------|
| ![Screen Shot 2025-05-14 at 10 49 33](https://github.com/user-attachments/assets/81b31992-9cf0-4f78-9be3-792d04718497) | ![Screen Shot 2025-05-14 at 10 49 42](https://github.com/user-attachments/assets/7e6d185d-585a-42db-a32c-98056049d405)|
| ![Screen Shot 2025-05-14 at 10 49 54](https://github.com/user-attachments/assets/9a1612e0-5bad-4054-a140-a80693eeb3e2) | ![Screen Shot 2025-05-14 at 10 49 59](https://github.com/user-attachments/assets/43806eb2-ca3d-4006-851e-64932a851389) | 
| ![Screen Shot 2025-05-14 at 10 50 …

feat: improve fieldset spacing and padding in contact form 

---

src/modules/search-time/selector/index.tsx

It was requested by @Sebstorvik / customer service to auto-select an early time when selecting a different date than today.
This PR does that, however does not change it when you have already selected another date, because then you probably have already set it yourself..
Acceptance Criteria:

feat: Auto-move time to early morning on date change away from today

---

src/page-modules/assistant/client/journey-planner/index.ts
src/page-modules/assistant/trip/index.tsx

Changed the `isLoadingFirstTrip` logic to check whether or not the data from the `useSWRInfinite` hook actually has some data or not.
Also set `persistSize` to `false`. We might not want to set this, but I found it to reduce load time of the page if you refresh, in case "Load more" has been pressed one too many times. Also, the page size is not persisted in e.g. the URL, so if someone is to share the URL they might think that the results that they see also is visible to the receiver when in fact it is not since the page size is lower. By not persisting the page size we might show a more realistic view for the sharer if they check the link before sending.
I also set `revalidateFirstPage: false`, since I did not see any benefit in revalidating the first results when loading more. I might …

fix: keep loading indicator when yet to get results

---

src/page-modules/assistant/client/journey-planner/index.ts

```ts
revalidateOnFocus: false,
revalidateIfStale: false,
revalidateOnReconnect: false,
```
Added these options to `useSWRInfinite` to _not_ automatically revalidate the data that has been fetched. Automatic revalidation might cause confusion for the user if it's not intended.

fix: don't revalidate trip pattern fetching

---

src/page-modules/assistant/client/journey-planner/index.ts

The app uses 5 for the amount of search attempts and 8 for the wanted number of trip patterns to show. It also uses 8 as the amount it wants when loading more, but that is not included as of yet in TPW.

fix: use same search config values as the app

---

src/components/button/button.tsx
src/components/map/use-map-tariff-zones.ts
src/modules/search-time/selector/__tests__/selector.test.tsx
src/modules/search-time/selector/time-selector-dropdown.tsx
src/modules/transport-mode/utils.ts
src/page-modules/assistant/client/journey-planner/index.ts
src/page-modules/assistant/details-body/index.tsx
src/page-modules/assistant/layout.tsx
src/page-modules/assistant/line-filter/index.tsx
src/page-modules/assistant/non-transit-pill/index.tsx
src/page-modules/assistant/types.ts
src/page-modules/assistant/utils.ts
src/page-modules/departures/client/geocoder/index.ts
src/page-modules/departures/details/estimated-call-rows.tsx
src/page-modules/departures/details/index.tsx
src/page-modules/departures/layout.tsx

And also clean up unused imports.
`useSWRImmutable` is the equivalent of using `useSWR` and passing the revalidate options with all of them set to `false`.

refactor: use immutable swr hook

---

e2e-tests/k6/conf/env.ts
e2e-tests/k6/measurements/measures.ts
e2e-tests/k6/measurements/metrics.ts
e2e-tests/k6/pages/assistant.ts
e2e-tests/k6/scenario/assistant.ts
src/page-modules/assistant/trip/trip-pattern/index.tsx

Update the k6-test with handling of accordion. Now, the tests open the details summary before opening the details through the _More details_ button.
NOTE! Added a test-id for the _More details_ button.

test: open accordion and then details

---

src/page-modules/assistant/client/journey-planner/index.ts

Experimental implementation of a hook that allows us to keep loading more pages until we get a new trip pattern. Instead of clicking "Load more" and nothing happens, the goal is to keep loading until something is received.

feat: load more until new results

---

src/modules/firebase/analytics.ts

There was a couple of consents missing 'denied' in analytics.ts

chore: deny missing consents in analytics.ts

---

src/page-modules/contact/components/form/fieldset/fieldset.module.css
src/page-modules/contact/components/form/fieldset/index.tsx
src/page-modules/contact/means-of-transport/forms/delayForm.tsx
src/page-modules/contact/means-of-transport/forms/driverForm.tsx
src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
src/page-modules/contact/means-of-transport/forms/stopForm.tsx
src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundCarForm.tsx
src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
src/page-modules/contact/ticketing/forms/app/appAccountForm.tsx
src/page-modules/contact/ticketing/forms/app/appTicketingForm.tsx
src/page-modules/contact/ticketing/forms/app/appTravelSuggestionForm.tsx
src/page-modules/contact/ticketing/forms/priceAndTicketTypesForm.tsx
src/page-modules/contact/ticketing/forms/travel-card/travelCardQuestionForm.tsx
src/page-modules/contact/ticketing/forms/webshop/webshopAccountForm.tsx
src/page-modules/contact/ticketing/forms/webshop/webshopTicketingForm.tsx

This PR extends the `Fieldset` component used in the contact form to optionally display a "required" indicator after the fieldset title. All fieldsets in the contact form that contain only mandatory textareas are updated to show this indicator. Lastly, an unused `error` parameter is removed.

feat: extend fieldset component title with optional requierd indicator

---

src/page-modules/contact/ticket-control/forms/feedbackForm.tsx

In this PR, ferry is removed from options, as there currently are none ticket controls on ferries.

feat: feedback ticket control - remove ferry from transportation options

---

src/page-modules/contact/means-of-transport/means-of-transport-form-machine.ts

Remove unexpected input property, causing an unexpected  validation error on submit.

fix: remove unexpected input property

---

src/translations/pages/contact.ts

Update translation to be more descriptive for the user.

chore: minor translation update

---

src/components/departure-time/__tests__/departure-time.test.tsx
src/modules/time-representation/index.ts

Fixes https://github.com/AtB-AS/kundevendt/issues/20475
Changed such that a departure now only hides the strikethrough if it differs by less than 15 seconds. This means we basicly always have strikethroughs when we have realtime, but we don't get this error:

fix: Decreased the threshold for significant difference

---

src/page-modules/contact/components/form/file-input.tsx
src/page-modules/contact/means-of-transport/forms/delayForm.tsx
src/page-modules/contact/means-of-transport/forms/driverForm.tsx
src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
src/page-modules/contact/means-of-transport/forms/stopForm.tsx
src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundCarForm.tsx
src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundTaxiForm.tsx
src/page-modules/contact/refund/forms/refund-ticket/appTicketRefund.tsx
src/page-modules/contact/refund/forms/refund-ticket/otherTicketRefund.tsx
src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
src/page-modules/contact/ticketing/forms/app/appAccountForm.tsx
src/page-modules/contact/ticketing/forms/app/appTicketingForm.tsx
src/page-modules/contact/ticketing/forms/app/appTravelSuggestionForm.tsx
src/page-modules/contact/ticketing/forms/priceAndTicketTypesForm.tsx
src/page-modules/contact/ticketing/forms/travel-card/travelCardQuestionForm.tsx
src/page-modules/contact/ticketing/forms/webshop/webshopAccountForm.tsx
src/page-modules/contact/ticketing/forms/webshop/webshopTicketingForm.tsx

Extend FileInput with IconLabel and include optional required indicator. Lastly, pass errorMessage as string instead of TranslatedString. 
This PR - does not change the appearance of the contact form yet, but facilitating upcoming changes.

update: extend file input component

---

src/page-modules/contact/components/form/form.module.css
src/page-modules/contact/components/form/textarea.tsx
src/page-modules/contact/refund/forms/refund-ticket/appTicketRefund.tsx
src/page-modules/contact/refund/forms/refund-ticket/otherTicketRefund.tsx

Extend textarea component with optional required indicator.

feat: extend textarea component with required indicator.

---

src/page-modules/assistant/__tests__/assistant.test.tsx
src/page-modules/assistant/client/journey-planner/index.ts
src/page-modules/assistant/layout.tsx
src/page-modules/assistant/trip/index.tsx
src/pages/assistant/index.tsx
src/tests/setup.ts

When navigating from the widget you would always get a double load, i.e. the results appeared pretty quickly, disappeared for a new load and then reappeared. This happened because of the removed `useEffect` in [/page-modules/assistant/layout.tsx](https://github.com/AtB-AS/planner-web/compare/strandlie/fix-double-search-bug?expand=1#diff-2272ca10f53868366f6e029fd3c7f06dccd13c9a6871b567534c7e0085104976) which added the filters to the URL, which then triggered a hard navigation and a reload. 
I solved this by better utilizing the server part of Next. Now when the URL does not have filters, just send a redirect to the correct URL with the correct filters for the county. 
[Link to video before](https://github.com/user-attachments/assets/c4446bcd-1cee-48dc-adab-10f1b3b1110b). Now the double …

fix: Double load problem when navigating from widget

---

src/translations/pages/contact.ts

Fixes typo in contact form: "Vel åtsak" -> "Vel årsak"

fix: typo in contact form

---

src/page-modules/assistant/details/trip-section/index.tsx
src/page-modules/assistant/journey-gql/trip-with-details.gql
src/page-modules/departures/details/index.tsx

This fixes a crash reported [here](https://oms-yzc6053.slack.com/archives/C075ZMJHZJN/p1757061248027859) and [here](https://mittatb.slack.com/archives/CR75QKX6G/p1756900426769319?thread_ts=1754128626.331689&cid=CR75QKX6G), where departures that operated on a different date than their serviceDate crashed the page.
This PR makes planner-web use the correct service date when navigating, as well as handles the case where date is wrong more gracefully (shows an error message).

fix: use serviceDate when navigating to departure details
