AtB-AS/planner-web

.github/release-drafter.yml
.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/tsc.yml
package.json
src/translations/__tests__/utils.test.ts
yarn.lock

Adds running tsc and tests on PRs and changes, and add similar release drafter as with webshop.

ci: adds tests and CI workflow

---

src/modules/api-server/utils.ts

Fixes issue with non-propagating error codes from upstream errors.

fix: propagate errors

---

package.json
src/layouts/global-data/index.ts
src/modules/api-server/index.ts
src/modules/cookies/__tests__/cookies-context.test.tsx
src/modules/cookies/cookies-context.tsx
src/page-modules/departures/__tests__/departure.test.tsx
src/pages/departures.tsx
src/tests/setup.ts
src/tests/utils.ts
vitest.config.ts
yarn.lock

- Adds tests for cookie contexts
- Add tests for page and getServersideProps for example Departures.

chore: adds tests as example and for plumbing different things

---

src/tests/setup.ts

This updates the env variable name for test setup after updating this in #9 .

fix: correct env variable name for test setup

---

src/assets/color-icon.tsx
src/assets/utils.ts
src/components/button/button.module.css
src/components/button/button.tsx
src/components/button/index.ts
src/components/button/link.tsx
src/components/button/utils.tsx
src/components/loading/index.tsx
src/components/loading/loading.module.css
src/translations/components/index.ts
src/translations/components/loading.ts
src/translations/index.ts
src/utils/css.ts

Needed for https://github.com/AtB-AS/kundevendt/issues/9147
I've added the button components from the webshop. From my understanding, the buttons will be the same in the planner-web as in the webshop, so it's nice to reuse them. 
There could be some good tests I'm not seeing that should be included. Let me know if you have any thoughts.

feat: button components

---

src/components/search/geolocation-button/index.tsx
src/components/typography/index.tsx
src/layouts/global-data/index.ts
src/modules/api-server/external-client.ts
src/modules/api-server/index.ts
src/page-modules/departures/__tests__/departure.test.tsx
src/page-modules/departures/index.ts
src/page-modules/departures/layout.tsx
src/page-modules/departures/nearest-stop-places/index.tsx
src/page-modules/departures/nearest-stop-places/nearest-stop-places.module.css
src/page-modules/departures/server/geocoder/encoders.ts
src/page-modules/departures/server/journey-planner/index.ts
src/page-modules/departures/server/journey-planner/journey-gql/departures.gql
src/page-modules/departures/server/journey-planner/journey-gql/nearest-stop-places.gql
src/page-modules/departures/server/journey-planner/journey-gql/stop-place.gql
src/page-modules/departures/server/journey-planner/validators.ts
src/page-modules/departures/types.ts
src/pages/departures/[[...id]].tsx

- Adds navigation from search input to location based and stop place based content.
- Adds listing stop places near a location
Splitting this task for collaboration. Need to follow up on things like proper design as a separate task.
<details>
</details>

feat: adds page for nearest stop places

---

src/page-modules/departures/__tests__/departure.test.tsx
src/page-modules/departures/departures.module.css
src/page-modules/departures/layout.tsx
src/page-modules/departures/nearest-stop-places/index.tsx
src/page-modules/departures/nearest-stop-places/nearest-stop-places.module.css
src/page-modules/departures/server/journey-planner/index.ts
src/page-modules/departures/server/journey-planner/journey-gql/nearest-stop-places.gql
src/page-modules/departures/server/journey-planner/validators.ts
src/translations/pages/departures.ts

Fixes https://github.com/AtB-AS/kundevendt/issues/9148

feat: adds design for stop place site

---

orgs/atb.json
orgs/fram.json
orgs/nfk.json
orgs/schema-validation.json
src/layouts/shared/footer.tsx
src/modules/org-data/index.tsx
src/translations/commons.ts

Adds org-specific config similar to Webshop but with JSON Schema validation and better structure. Also with support for several language-specific URLs. 
Fixes https://github.com/AtB-AS/kundevendt/issues/10305
Example
```json
{
"$schema": "./schema-validation.json",
"orgId": "nfk",
"supportEmail": "sentrumsterminalen@boreal.no",
"fylkeskommune": {
"logoSrc": "/nfk_fylkeskommune.svg",
"logoSrcDark": "/nfk_fylkeskommune_dark.svg",
"name": "Nordland fylkeskommune"
},
"urls": {
"privacyDeclarationUrl": {
"default": "https://www.reisnordland.no/personvern-og-cookies"
},
"accessibilityStatementUrl": {
"default": "https://uustatus.no/nb/erklaringer/publisert/ae5bc315-272a-469e-b4cb-8ba5164ea988"
},
"supportUrl": {
"default": "https://www.reisnordland.no/kontaktskjema",
"en-US": …
```

feat: adds org specific config

---

src/page-modules/departures/__tests__/departure.test.tsx
src/page-modules/departures/client/index.ts
src/page-modules/departures/client/journey-planner/index.ts
src/page-modules/departures/server/journey-planner/index.ts
src/page-modules/departures/server/journey-planner/journey-gql/estimated-calls.gql
src/page-modules/departures/server/journey-planner/validators.ts
src/page-modules/departures/stop-place/index.tsx
src/pages/api/departures/journey-planner.ts

This PR includes new functionality for loading more departures for a specific quay. 
Closes https://github.com/AtB-AS/kundevendt/issues/9149

feat: load more departures for a specific quay

---

package.json
src/components/departure-date-selector/departure-date-selector.module.css
src/components/departure-date-selector/index.tsx
yarn.lock

Added `framer-motion` as a dependency and added some animation to the departure date selector.

style: add animation to departure date selector

---

src/components/departure-date-selector/index.tsx
src/components/transport-mode-filter/transport-mode-filter.module.css
src/page-modules/assistant/assistant.module.css
src/page-modules/assistant/layout.tsx
src/page-modules/departures/departures.module.css
src/page-modules/departures/layout.tsx

Adds enter/exit animation to the alternatives section.
<details><summary>Screenshots</summary>
<p>
</p>
</details>

style: add animation to alternatives section

---

src/pages/index.tsx

Set the frontpage as Assistant page

feat: set assistant as front page

---

scripts/build-docker.sh

ci: fix build

---

src/translations/modules/layout.ts

Fixes https://github.com/AtB-AS/kundevendt/issues/15097

fix: change "norsk" to "norsk (bokmål)"

---

src/translations/pages/assistant.ts

Fix typo when loading suggestions.

fix: fix typo when loading suggestions

---

src/translations/common/titles.ts

This should probably be updated to proper titles as well. In Figma the title is "AtB Reisesøk". Not sure what it shall be called.

fix: fix page title for AtB

---

src/page-modules/assistant/server/journey-planner/index.ts
src/page-modules/assistant/types.ts
src/page-modules/departures/server/journey-planner/index.ts
src/pages/api/assistant/trip.ts
src/pages/assistant/index.tsx

Convert transport mode filter to correct type.

fix: convert transport mode filter to correct type

---

src/page-modules/assistant/server/journey-planner/index.ts
src/page-modules/assistant/server/journey-planner/journey-gql/trip.gql
src/page-modules/assistant/server/journey-planner/validators.ts
src/page-modules/assistant/trip/trip-pattern/__tests__/trip-pattern.fixture.ts
src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/__tests__/trip-pattern.fixture.ts
src/pages/api/assistant/trip.ts
src/pages/assistant/index.tsx

Improves performance by:
- Making more calls in parallell
- Removing unused data from trip planner query
- Increasing search window for trips.
- Fixing bug in do-while loop condition.

fix: general performance for travel planner

---

src/translations/pages/departures.ts

Fixes https://github.com/AtB-AS/kundevendt/issues/15754

fix: update departure from text

---

src/modules/situations/situation-message-box.tsx
src/page-modules/assistant/details/trip-section/index.tsx
src/page-modules/assistant/server/journey-planner/index.ts
src/page-modules/assistant/server/journey-planner/journey-gql/trip-with-details.gql
src/page-modules/assistant/server/journey-planner/validators.ts

This PR adds situations and notices to the travel details page. 
Part of closing https://github.com/AtB-AS/kundevendt/issues/15639

feat: situations and notices on travel details

---

src/page-modules/assistant/details/index.tsx
src/translations/pages/assistant.ts

This PR adds what unit the walking distance is in and removes the decimals from the distance. 
Closes https://github.com/AtB-AS/kundevendt/issues/15792

feat: walking distance unit and format decimals

---

src/widget/widget.ts

Adds support for searching on specific arrival time and departure time.
Part of https://github.com/AtB-AS/kundevendt/issues/14939

feat: Add support for search date for widget

---

src/page-modules/departures/client/geocoder/index.ts
src/page-modules/departures/layout.tsx

Makes searching for departures a bit more ergonomic. Will search for departures when selecting place
- Auto search on select
- Reduces Search debounce
- Avoids revalidation on autocomplete (calling autocomplete API unnecessary amount of times without any additional value)

fix: improves search for departments and autoselects

---

src/translations/pages/assistant.ts

Fixes https://github.com/AtB-AS/kundevendt/issues/15812

fix: assistant details header back link text

---

src/page-modules/departures/server/geocoder/encoders.ts
src/widget/widget.ts

Related to https://github.com/AtB-AS/kundevendt/issues/14939
Design can be improved at some point though

fix: Handle no search result for widget

---

src/components/search/search.module.css
src/page-modules/assistant/assistant.module.css
src/page-modules/departures/departures.module.css

Fixes https://github.com/AtB-AS/kundevendt/issues/15750
It was reported that the search fields in mobile view became a bit too small. 
<details>
<summary>screenrecording</summary>
https://github.com/AtB-AS/planner-web/assets/59939294/951ab3ee-d715-4047-a2d5-042be9006ca3
</details>

fix: Minor change to improve layout in mobile view. 

---

src/translations/pages/assistant.ts

Request from Christoffer to change the assistant page search title

fix: assistant page search title

---

orgs/fram.json

Fixes URLs and email in footer

fix: removes wrong SoMe links

---

src/modules/search-time/selector/__tests__/selector.test.tsx
src/modules/search-time/types.ts
src/translations/modules/search-time.ts

Swapping departBy and arriveBy in assistant mode. Also replacing Avgang with Avreise

feat: swap departBy and arriveBy in assistant

---

src/modules/search-time/selector/selector.module.css
src/widget/widget.module.css

Update selected color of search time selector.

fix: update selected color of search time selector

---

middleware.js
next.config.js

Testing setting specific headers for frammr specific, just to fix temp issue. Should be fixed permanently later

temp: fixes cors for temp

---

package.json
src/components/map/map.tsx
src/components/map/use-map-tariff-zones.ts
src/modules/firebase/index.ts
src/utils/reference-data.ts
yarn.lock

This implements functionality to draw tariff zone boundaries in the map. 
Closes https://github.com/AtB-AS/kundevendt/issues/15775

feat: tariff zones in map

---

src/widget/widget.ts

Closing https://github.com/AtB-AS/kundevendt/issues/16352
Only including widget.ts changes so that new version can be generated together with other changes.

fix: remove duplicate aria-labelledby lables found by ARC

---

package.json
src/components/icon/utils.ts
src/page-modules/assistant/details/trip-section/index.tsx
src/page-modules/assistant/details/trip-section/walk-section.tsx
src/page-modules/departures/details/index.tsx
yarn.lock

👋 Hello hello, first time contributor here! 
Don't mind me, I'm just updating some icon sizes.
- Changes small icon size to 16
- Adds a new icon size, xSmall = 12
fixes https://github.com/AtB-AS/kundevendt/issues/3834

feat: update icon sizes

---

orgs/atb.json
orgs/fram.json
orgs/nfk.json
orgs/schema-validation.json
src/modules/org-data/index.tsx
src/page-modules/assistant/__tests__/assistant.test.tsx
src/page-modules/assistant/assistant.module.css
src/page-modules/assistant/layout.tsx
src/page-modules/assistant/line-filter/index.tsx
src/page-modules/assistant/line-filter/line-filter.module.css
src/page-modules/assistant/server/journey-planner/index.ts
src/page-modules/assistant/server/journey-planner/journey-gql/trip.gql
src/page-modules/assistant/trip-query-fetcher.ts
src/page-modules/assistant/trip/index.tsx
src/page-modules/assistant/types.ts
src/page-modules/assistant/utils.ts
src/pages/api/assistant/trip.ts
src/translations/pages/assistant.ts

This adds the functionality to filter lines in the travel search. 
Closes https://github.com/AtB-AS/kundevendt/issues/16679

feat: line filter in search

---

src/components/map/__tests__/map.test.tsx
src/components/map/index.tsx
src/components/map/map-loading.tsx
src/components/map/map.module.css
src/components/map/map.tsx
src/translations/components/map.ts

Lazy load map and deactivate SSR. Hopefully reduces some initializations of the map.

fix: only load map on client

---

src/modules/trip-details/use-realtime-text.ts
src/page-modules/assistant/details/trip-section/estimated-calls-section.tsx
src/page-modules/assistant/details/trip-section/index.tsx
src/page-modules/assistant/details/trip-section/realtime-section.tsx
src/page-modules/assistant/details/trip-section/trip-section.module.css
src/page-modules/assistant/server/journey-planner/index.ts
src/page-modules/assistant/server/journey-planner/journey-gql/trip-with-details.gql
src/page-modules/assistant/server/journey-planner/journey-gql/via-trip-with-details.gql
src/page-modules/assistant/server/journey-planner/validators.ts

This PR adds the realtime indicator in the details view. 
Closes https://github.com/AtB-AS/kundevendt/issues/17227

feat: realtime indicator for details view

---

src/components/labled-input/index.tsx

Fixes https://github.com/AtB-AS/kundevendt/issues/17245

fix: a11y for filter search

---

src/components/labled-input/index.tsx
src/components/message-box/index.tsx

Fixes so message boxes read errors using aria roles

fix: messagebox error validity

---

src/components/empty-message/index.tsx
src/components/loading/index.tsx
src/components/screen-reader-only/index.tsx
src/components/screen-reader-only/screen-reader-only.module.css
src/components/search/geolocation-button/index.tsx
src/page-modules/assistant/trip/index.tsx
src/page-modules/departures/nearest-stop-places/index.tsx
src/page-modules/departures/stop-place/index.tsx
src/translations/components/geolocation-button.ts
src/translations/pages/assistant.ts
src/translations/pages/departures.ts

Fixes https://github.com/AtB-AS/kundevendt/issues/17360

fix: adds better screen reader support for loading / results states

---

src/utils/date.ts

Temporary fix to adjust for summer time. Works fine in CET timezone, but need more testing in other timezones.
https://github.com/AtB-AS/planner-web/assets/59939294/b1793e1e-160d-45e7-bb9b-420ac584e08a

fix: temporary fix to adjust for summer time

---

src/components/search/search.tsx
src/translations/components/index.ts
src/translations/components/search.ts

Fixes https://github.com/AtB-AS/kundevendt/issues/17498

fix: translates a11y status texts on downshift

---

src/modules/global-messages/converters.ts
src/modules/global-messages/index.tsx
src/modules/global-messages/types.ts

This includes a new context provider for global messages. The context provider is not in use yet, but will be when completing https://github.com/AtB-AS/kundevendt/issues/17725.

feat: global messages context provider

---

orgs/troms.json
src/translations/modules/layout.ts

Svipper do not want their fylkeskommune logo or social media links in the footer.

fix: footer content for Svipper

---

src/modules/api-server/requesters/types.ts
src/page-modules/contact/content/content.module.css
src/page-modules/contact/content/index.tsx
src/page-modules/contact/server/contact/index.ts
src/page-modules/contact/server/index.ts
src/page-modules/contact/server/types.ts
src/page-modules/contact/utils.ts
src/pages/api/contact/index.ts
src/pages/contact/index.tsx

- Added logic to interact with contact API.
- `handlerWithContactFormClient` was created to more easily retrieve information through the jouneryPlanner api later.

feat: add logic to interact with with contact api.

---

src/components/map/map.tsx
src/modules/firebase/analytics.ts

Add new log event to further investigate excessive Mapbox loads.
Part of https://github.com/AtB-AS/kundevendt/issues/18810

chore: add initialize map log event

---

src/page-modules/contact/components/section-card/index.ts
src/page-modules/contact/components/section-card/section-card.module.css
src/page-modules/contact/components/section-card/section-card.tsx

Component to display the content of a form. The content is set through children props.

feat: add contact section card component

---

src/page-modules/contact/index.ts
src/page-modules/contact/lines/use-lines.ts
src/page-modules/contact/server/index.ts
src/page-modules/contact/server/journey-planner/index.ts
src/page-modules/contact/server/journey-planner/journey-gql/lines.gql
src/page-modules/contact/server/journey-planner/validators.ts
src/pages/api/contact/lines.ts

This extends the contact form client with a journey-planner API for fetching lines. This is needed for the new contact form. I've created a custom hook that can be used to filter lines by mode and filter quays by line. 
Something to consider for later:
- add cache
- don't fetch all lines per authority, but query by transport mode / line etc. This would decrease the initial data load
<details>
<summary>Example usage </summary>
```ts
export default function example() {
const { lines, error, isLoading, getLinesByMode, getQuaysByLine } = useLines();
const [mode, setMode] = useState<TransportModeType>();
const [line, setLine] = useState<Line>();
const [fromQuay, setFromQuay] = useState<Line['quays'][0]>();
const [toQuay, setToQuay] = useState<Line['quays'][0]>();
return (
<form> …
```

feat: custom hook for lines

---

src/page-modules/contact/server/contact/index.ts
src/page-modules/contact/server/types.ts
src/page-modules/contact/ticket-control/complaint/feeComplaintForm.tsx
src/page-modules/contact/ticket-control/feedback/feedbackForm.tsx
src/pages/api/contact/ticket-control.ts

Updated the contact API to have a ticket-control specific API endpoint and updated the data structure. This needs to be fine-tuned later, but works for now

feat: ticket-control api endpoint

---

src/page-modules/contact/ticket-control/ticket-control.module.css

Fix to avoid inline jump bug. 
<details>
<summary>Before</summary>
https://github.com/user-attachments/assets/9aa57a7a-92e8-4f02-a0db-cd0d4b1a11b3
</details>
<details>
<summary>After</summary>
https://github.com/user-attachments/assets/a31ec93a-1519-4014-9cac-9cf2a3434386
</details>

fix: inline jump bug

---

src/page-modules/contact/components/input/checkbox.tsx
src/page-modules/contact/components/input/input.module.css
src/page-modules/contact/components/section-card/section-card.module.css
src/page-modules/contact/components/section-card/section-card.tsx
src/page-modules/contact/layouts/contact-page-layout.tsx
src/page-modules/contact/layouts/ticket-control-page-layout.tsx
src/page-modules/contact/ticket-control/complaint/feeComplaintForm.tsx
src/page-modules/contact/ticket-control/ticket-control.module.css
src/translations/pages/contact.ts

I've done some work to start using the design-system more. This PR adds a new checkbox and Typo-component usage

feat: checkbox and ticket-control typo

---

src/page-modules/contact/components/input/checkbox.tsx
src/page-modules/contact/components/input/error-message.tsx
src/page-modules/contact/components/input/input.module.css
src/page-modules/contact/components/input/input.tsx
src/page-modules/contact/components/input/radio.tsx
src/page-modules/contact/components/input/select.tsx
src/page-modules/contact/components/input/textarea.tsx
src/page-modules/contact/layouts/ticket-control-page-layout.tsx
src/page-modules/contact/ticket-control/complaint/feeComplaintForm.tsx
src/page-modules/contact/ticket-control/feedback/feedbackForm.tsx
src/page-modules/contact/ticket-control/feedback/feedbackformMachine.ts

This PR touches multiple things, making it a bit hard to read, and I apologize for that. The PR: 
- introduces a error component
- includes new form components (textarea, radio, select)
- refactor to use the Typo component
- remove guard for TransportMode as it didn't work properly

feat: form components and refactoring

---

src/page-modules/contact/index.ts
src/page-modules/contact/machineEvents.ts
src/page-modules/contact/ticket-control/complaint/complaintFormMachine.ts
src/page-modules/contact/ticket-control/complaint/index.tsx
src/page-modules/contact/ticket-control/feedback/feedbackForm.tsx
src/page-modules/contact/travel-guarantee/index.tsx
src/page-modules/contact/validation/commonFieldValidator.ts
src/pages/contact/ticket-control/complaint/index.tsx
src/translations/pages/contact.ts

Closes https://github.com/AtB-AS/kundevendt/issues/18906
This PR updates the complaint form and corresponding state machine.Also, more error messages are added to the commonFieldValidator.

chore: update the complaint form and state machine

---

src/page-modules/contact/components/input/file.tsx
src/page-modules/contact/components/input/input.module.css
src/page-modules/contact/machineEvents.ts
src/page-modules/contact/ticket-control/complaint/complaintFormMachine.ts
src/page-modules/contact/ticket-control/complaint/index.tsx
src/page-modules/contact/ticket-control/feedback/feedbackformMachine.ts
src/page-modules/contact/ticket-control/feedback/index.tsx
src/page-modules/contact/utils.ts
src/translations/pages/contact.ts

This includes a new input for files that is used by the complaint and feedback form.

feat: file attachments

---

src/page-modules/contact/means-of-transport/forms/delayForm.tsx
src/page-modules/contact/means-of-transport/forms/driverForm.tsx
src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
src/page-modules/contact/means-of-transport/forms/stopForm.tsx
src/page-modules/contact/means-of-transport/forms/transportationForm.tsx

Remove unused property from form props.

chore: remove unused property from form props

---

package.json
yarn.lock

https://github.com/AtB-AS/kundevendt/issues/18263

chore: update generate-assets dependency to v13.0.2

---

src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
src/page-modules/contact/ticket-control/forms/postponePayment.tsx
src/page-modules/contact/ticket-control/ticket-control-form-machine.ts

Fix uncontrolled input error, that appears on the console.log. Also, update the customerNumber input to display the correct error messages.

chore: fix uncontrolled input error

---

src/page-modules/contact/components/section-card/section-card.tsx
src/page-modules/contact/means-of-transport/forms/delayForm.tsx
src/page-modules/contact/means-of-transport/forms/driverForm.tsx
src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
src/page-modules/contact/means-of-transport/forms/stopForm.tsx
src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
src/page-modules/contact/means-of-transport/index.tsx
src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
src/page-modules/contact/ticket-control/forms/postponePayment.tsx
src/page-modules/contact/ticket-control/index.tsx
src/page-modules/contact/travel-guarantee/form-selector.tsx
src/page-modules/contact/travel-guarantee/index.tsx

Update type of title property inside `SeactionCardProps` from `TranslatedString` to `string`.

chore: update type of prop in section card

---

src/page-modules/contact/layouts/layout.module.css

fix: contact page layout responsive design

---

src/page-modules/contact/means-of-transport/events.ts
src/page-modules/contact/means-of-transport/forms/delayForm.tsx
src/page-modules/contact/means-of-transport/forms/driverForm.tsx
src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
src/page-modules/contact/means-of-transport/forms/stopForm.tsx
src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
src/page-modules/contact/means-of-transport/means-of-transport-form-machine.ts
src/page-modules/contact/server/contact/index.ts
src/page-modules/contact/validation/commonInputValidator.ts
src/pages/api/contact/means-of-transport.ts
src/translations/pages/contact.ts

- Extends the API with submitMeansOfTransportForm.
- Updates the means of transport state machine. 
- Removes exessive property from commonInputValidator.

feat: update means of transport state machine and forms

---

src/page-modules/contact/components/input/file.tsx
src/page-modules/contact/components/input/input.module.css

- Extend file input icon to use theme colours.
- Make FileInput reachable by using TAB, and possible to open using both space and enter. 
- Add hover to radioBox, iconsButton and FileInput.

chore: minor improvements of FileInput component.

---

src/page-modules/contact/group-travel/group-travel.module.css
src/page-modules/contact/group-travel/index.tsx
src/page-modules/contact/layouts/contact-page-layout.tsx

Make submit button width 100% outside of the section card and make the form available through the contact layout

feat: make group travel form available

---

src/page-modules/contact/server/journey-planner/index.ts

fix: sort lines by public code

---

src/page-modules/contact/contact.module.css
src/page-modules/contact/group-travel/group-travel.module.css
src/page-modules/contact/group-travel/index.tsx
src/page-modules/contact/means-of-transport/index.tsx
src/page-modules/contact/ticket-control/index.tsx
src/page-modules/contact/ticketing/index.tsx
src/page-modules/contact/travel-guarantee/index.tsx

Ensure that the submit button has the same width for all forms.

fix: width form submit button

---

src/page-modules/contact/components/form/checkbox.tsx
src/page-modules/contact/components/form/description-modal.tsx
src/page-modules/contact/components/form/error-message.tsx
src/page-modules/contact/components/form/file-input.tsx
src/page-modules/contact/components/form/form.module.css
src/page-modules/contact/components/form/input.tsx
src/page-modules/contact/components/form/radio.tsx
src/page-modules/contact/components/form/searchable-select/searchable-select.tsx
src/page-modules/contact/components/form/select.tsx
src/page-modules/contact/components/form/textarea.tsx

- Rename from input.module.css to form.module.css. 
- Update from `justify-content: start;` to `justify-content: flex-start;` to avoid warning in terminal.

chore: minor update of styling in contact components

---

next.config.js
package.json
src/modules/transport-mode/icon/index.tsx
src/widget/vite.config.js
yarn.lock

Using latest `@atb-as/design-system` and `@atb-as/generate-assets`

feat: Upgraded design system

---

src/page-modules/contact/ticketing/events.ts
src/page-modules/contact/ticketing/forms/webshop/index.tsx
src/page-modules/contact/ticketing/forms/webshop/webshopAccountForm.tsx
src/page-modules/contact/ticketing/forms/webshop/webshopTicketingForm.tsx
src/page-modules/contact/ticketing/forms/webshopForm.tsx
src/page-modules/contact/ticketing/index.tsx
src/page-modules/contact/ticketing/ticketingStateMachine.ts
src/translations/pages/contact.ts

This PR provides a form for webshop, under the ticketing page.

feat: ticketing webshop form

---

src/page-modules/contact/components/form/file-input.tsx
src/page-modules/contact/components/form/form.module.css
src/translations/pages/contact.ts

Add optional error message to fileInput component.

feat: add optional error message into file input component

---

src/page-modules/contact/components/form/form.module.css
src/page-modules/contact/components/form/searchable-select/searchable-select.tsx

**Enhance SearchableSelector** behavior so that it automatically clears the inputValue when value === undefined, the component is not focused, and inputValue is not empty. Specifically, in the case of selecting a transportMode and a related line, the inputValue for line should automatically clear whenever transportMode is changed. However, the inputValue should not clear while the user is actively typing and the value remains undefined.
**Update the styling of Checkbox and InputFile** components: update the Checkbox with a smoother border-radius and apply a clear, distinct border to InputFile when focused, improving the user interface consistency and focus handling.

chore: minor improvements to form components

---

src/page-modules/contact/components/form/form.module.css
src/page-modules/contact/components/form/searchable-select/searchable-select.tsx

Remove grey background on disabled from SearchableSelect.

chore: update  searchable select disabled colour

---

src/page-modules/contact/components/section-card/section-card.module.css

Update margin of section card component to create some more space between the window and the the left and right side of the section card. 
<details>
<summary>Before update</summary>
</details>
<details>
<summary>After update</summary>
</details>

chore: update margin of section card component

---

src/page-modules/contact/contact.module.css
src/page-modules/contact/group-travel/index.tsx
src/page-modules/contact/means-of-transport/index.tsx
src/page-modules/contact/ticket-control/index.tsx
src/page-modules/contact/ticketing/index.tsx
src/page-modules/contact/travel-guarantee/index.tsx

Align width of submit button to match width of section card.
Before:
After:

fix: update width of submit button

---

src/page-modules/contact/ticketing/events.ts
src/page-modules/contact/ticketing/forms/app/appTicketingForm.tsx
src/page-modules/contact/ticketing/forms/refund/appTicketRefund.tsx
src/page-modules/contact/ticketing/forms/refund/index.tsx
src/page-modules/contact/ticketing/forms/refund/otherTicketRefund.tsx
src/page-modules/contact/ticketing/forms/webshop/webshopTicketingForm.tsx
src/page-modules/contact/ticketing/index.tsx
src/page-modules/contact/ticketing/ticketingStateMachine.ts
src/translations/pages/contact.ts

This PR provides refund forms, under the ticketing page.

feat: add ticketing refund forms 

---

src/page-modules/contact/layouts/contact-page-layout.tsx

Extend the contact page layout with link to ticketing forms.

feat: add link to ticketing forms 

---

src/page-modules/contact/components/form/form.module.css
src/page-modules/contact/components/form/input.tsx

Extend input component with disabled property

feat: extend input component with disabled property

---

orgs/fram.json
src/translations/modules/layout.ts

Update link to link to contact form.

feat: link to contact form

---

src/page-modules/contact/components/form/form.module.css
src/page-modules/contact/components/form/searchable-select/searchable-select.tsx

Add background colour to searchable to highlight when disabled.

feat: add styling to highlight whenever the searchable selector is disabled

---

src/translations/pages/contact.ts

fix: translation typos

---

src/page-modules/contact/lost-property/index.tsx
src/translations/pages/contact.ts

Closes https://github.com/AtB-AS/kundevendt/issues/19580

feat: update translation text in lost property page 

---

src/page-modules/contact/ticketing/forms/webshop/webshopTicketingForm.tsx
src/translations/pages/contact.ts

Closes https://github.com/AtB-AS/kundevendt/issues/19591#issue-2682935978
Adding bullet points to detail list.

fix:  add bullet points to detail list

---

package.json
yarn.lock

Upgrade atb-as/theme to version 11.2.0.

feat: upgrade colour theme to version 11.2.0

---

orgs/schema-validation.json
orgs/vkt.json

Sett følgende lenker fro Telemark:
Priser: https://www.vkt.no/reise/billetter-og-priser/
Kontakt oss: https://www.vkt.no/om-oss/kontakt-oss/
Reisevilkår: https://www.vkt.no/vilkar/
Personvern: https://www.vkt.no/vilkaar-og-personvern/personvern/
Tilgjengelighetserklæring: https://www.vkt.no/om-oss/tilgjengelighetserklaering/

feat: add links for Telemark

---

package.json
yarn.lock

New text colors and illustrations for VKT.

chore: upgrade assets and theme packages

---

src/page-modules/assistant/trip/index.tsx
src/page-modules/departures/layout.tsx

Closes AtB-AS/kundevendt#19615

feat: Update today text

---

src/page-modules/assistant/trip/index.tsx
src/translations/dictionary.ts

Related to AtB-AS/kundevendt#19615

Aligned date-views with the app

---

src/page-modules/assistant/trip/index.tsx

Related to AtB-AS/kundevendt#19615

fix: Added missing dash

---

src/page-modules/contact/refund/refundFormMachine.ts
src/page-modules/contact/ticketing/ticketingStateMachine.ts

Update state machines to avoid building errors when building widget. The solution is similar to the one posted in the issue https://github.com/statelyai/xstate/issues/5090.

fix: update state machines to avoid building errors when building widget

---

src/page-modules/contact/means-of-transport/events.ts
src/page-modules/contact/means-of-transport/forms/delayForm.tsx
src/page-modules/contact/means-of-transport/forms/driverForm.tsx
src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
src/page-modules/contact/means-of-transport/forms/stopForm.tsx
src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
src/page-modules/contact/means-of-transport/index.tsx
src/page-modules/contact/means-of-transport/means-of-transport-form-machine.ts

- Update state machine to avoid having to force re-render on submit.
- Update a few body property names to match the property names expected by the server.

fix: update state machine of the means of transport page in the contact form

---

README.md
src/page-modules/assistant/details/trip-section/index.tsx
src/page-modules/assistant/server/journey-planner/index.ts
src/page-modules/assistant/server/journey-planner/journey-gql/trip-with-details.gql
src/page-modules/assistant/server/journey-planner/journey-gql/trip.gql
src/page-modules/assistant/server/journey-planner/journey-gql/via-trip-with-details.gql
src/page-modules/assistant/server/journey-planner/journey-gql/via-trip.gql
src/page-modules/assistant/server/journey-planner/validators.ts
src/page-modules/assistant/trip/trip-pattern/__tests__/trip-pattern.fixture.ts
src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/__tests__/trip-pattern-header.test.tsx
src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/__tests__/trip-pattern.fixture.ts

Included the quay description when displaying trip details. This is already shown in the departures view.

feat: quay description in trip details

---

src/page-modules/contact/server/contact/index.ts
src/page-modules/contact/ticket-control/events.ts
src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
src/page-modules/contact/ticket-control/forms/postponePayment.tsx
src/page-modules/contact/ticket-control/index.tsx
src/page-modules/contact/ticket-control/ticket-control-form-machine.ts

- Update state machine to avoid having to force re-render on submit. 
- Update a few body property names to match the property names expected by the server.

fix: update state machine of the ticket control page in the contact form 

---

src/components/search/search.module.css
src/components/search/search.tsx

Adds styling for new dropdown component from https://github.com/AtB-AS/kundevendt/issues/20062
https://github.com/user-attachments/assets/e332f18a-ea7c-4ea2-ba5c-e7c7a7b52bb4
follow up to https://github.com/AtB-AS/planner-web/pull/493
closes https://github.com/AtB-AS/kundevendt/issues/20062

feat: update location search dropdown styling

---

src/pages/api/departures/autocomplete.ts
src/pages/api/departures/reverse.ts

A step along the way for AtB-AS/kundevendt#20014
Currently you get these errors:

Added Coretrek staging environment as a valid cors origin

---

src/translations/pages/contact.ts

Update translations in contact form.

update: update translations in contact form

---

e2e-tests/k6/.gitignore
e2e-tests/k6/conf/env.ts
e2e-tests/k6/conf/options.ts
e2e-tests/k6/pages/assistant.ts
e2e-tests/k6/pages/departures.ts
e2e-tests/k6/scenario/assistant.ts
e2e-tests/k6/scenario/departures.ts
src/components/search/swap-button/index.tsx
src/page-modules/assistant/details/index.tsx
src/page-modules/assistant/layout.tsx
src/page-modules/departures/details/estimated-call-rows.tsx
src/page-modules/departures/layout.tsx

Add improvements for `k6` tests to solve https://github.com/AtB-AS/kundevendt/issues/20266. Local test results are given [here](https://github.com/AtB-AS/kundevendt/issues/20266#issuecomment-2735707830).
> [!NOTE]
> Added some test ids for easier use in the `k6` tests.

test: k6 improvements for core web vitals

---

src/page-modules/assistant/server/journey-planner/validators.ts
src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/utils.ts

Closes https://github.com/AtB-AS/kundevendt/issues/19888

chore: Add to estimated calls for trip search

---

orgs/atb.json

Related to AtB-AS/kundevendt#20014

fix: Update URL to privacy policy

---

package.json
src/page-modules/assistant/journey-gql/trip-with-details.gql
src/page-modules/assistant/journey-gql/via-trip-with-details.gql
src/page-modules/assistant/journey-gql/via-trip.gql
src/page-modules/assistant/server/journey-planner/index.ts

The date was not included in the server, closes https://github.com/AtB-AS/kundevendt/issues/19888

fix: Notices to estimated call

---

src/components/map/map.tsx
src/components/map/static-map.tsx
src/components/map/types.ts
src/components/map/use-map-interactions.ts
src/components/map/use-map-legs.ts
src/components/map/use-map-pin.ts
src/components/map/utils.ts
src/page-modules/assistant/server/journey-planner/index.ts

Fixes feedback from AtB-AS/planner-web#512
- Adds missing cursor-information, such that "Load more" now actually loads more trips.
- Fixes types of Position/Coordinates such that map now works as intended

Fix issues from types-PR

---

src/components/map/map-header.tsx
src/page-modules/assistant/__tests__/assistant.test.tsx
src/page-modules/assistant/details/utils.ts
src/page-modules/assistant/trip-query-fetcher.ts
src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/__tests__/trip-pattern.fixture.ts
src/page-modules/assistant/types.ts
src/page-modules/assistant/utils.ts
src/page-modules/departures/fetch-departure-query.ts
src/page-modules/departures/utils.ts

This reverts commit d1472c41635341b586daee4c45c698cf8f5c3a48.
Reverting until the issue with the widgets are fixed, the fix is not trivial.

Revert "feat: use autocomplete data instead of reverse geocoder for trip search and departure (#506)"

---

src/page-modules/assistant/details-body/index.tsx
src/page-modules/assistant/trip/trip-pattern/index.tsx
src/page-modules/assistant/trip/trip-pattern/trip-pattern.module.css
src/translations/pages/assistant.ts

Another iteration on AtB-AS/kundevendt#19334 
Improves usability by making the "See more"-button stay in the same place, and also tweaks the aria-labels.

feat: Improved usability for accordion

---

src/components/map/map.module.css
src/page-modules/assistant/trip/trip-pattern/trip-pattern.module.css

Closes AtB-AS/kundevendt#19334

fix: Fixed missing button-border in dark mode

---

e2e-tests/assistant-view.spec.ts
e2e-tests/fram-specific/assistant.spec.ts
src/components/search/search.module.css
src/page-modules/assistant/__tests__/assistant.test.tsx
src/page-modules/assistant/assistant.module.css
src/page-modules/departures/departures.module.css
src/translations/components/tab-link.ts
src/translations/pages/assistant.ts
src/translations/pages/departures.ts
src/widget/widget.ts

Closes: https://github.com/AtB-AS/kundevendt/issues/19332
Now:

Fix: Missing border for departures

---

src/page-modules/contact/components/form/time-selector.tsx
src/page-modules/contact/means-of-transport/forms/delayForm.tsx
src/page-modules/contact/means-of-transport/forms/driverForm.tsx
src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundCarForm.tsx
src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundTaxiForm.tsx
src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
src/page-modules/contact/utils.ts

Id is added to enable automatic scroll to error message in contact form.

feat: add id tag to time selector component in contact form

---

src/page-modules/departures/client/geocoder/index.ts

fix: Fixed swapped lat/lon for autocomplete

---

package.json
yarn.lock

Updating assets package so the planner web use latest assets

chore: update assets package to latest

---

src/translations/pages/contact.ts

Some minor translation fixes to the contact form.

fix: contact form translations

---

src/page-modules/assistant/trip-query-fetcher.ts

There was an issue when fetching the locations from the query. The autocomplete in `trip-query-fetcher.ts` did not take into account neither coordinates nor if it should only show stop places. So when we searched only by name, e.g. "Solnes", and our focus point/position is nowhere near that place we ended up with not getting the correct feature in the result from autocomplete. 
It seems to me that we will always have the properties for id and coordinates when we have a location feature, i.e. when we have set a from place we will have all of `fromName/fromId/fromLat/fromLon/fromLayer`. Based on that assumption we can simplify some of the logic, and also use the coordinates when calling the autocomplete. That way we should in most cases end up with a result that should have the correct …

refactor: use coordinates when searching for location

---

package.json
src/components/venue-icon/index.tsx
src/modules/transport-mode/icon/index.tsx
src/page-modules/assistant/details-body/index.tsx
src/page-modules/assistant/trip/trip-pattern/index.tsx
src/page-modules/contact/layouts/contact-page-layout.tsx
yarn.lock

Implements changes from https://github.com/AtB-AS/design-system/pull/321
Also changes some Entur icons to our icons.

feat: update transportation icons

---

src/modules/logging/log-page-access.ts
src/page-modules/assistant/details-body/index.tsx
src/page-modules/assistant/details/index.tsx
src/page-modules/assistant/details/utils.ts

Closes https://github.com/AtB-AS/kundevendt/issues/20239

fix: Retain via and line number when navigating back

---

src/page-modules/contact/validation/validationRules.ts
src/translations/pages/contact.ts

New customer numbers are 8 digits long. Add validation to support

fix(contact): support 8 digit customer numbers

---

src/page-modules/assistant/assistant.module.css

fix: Fixed very tiny travel suggestions
